# Привет, ревьюер!

Вот на эту всю графоманию я затратил $32$ часа.\
На написание и продумывание одной только функции, которая помогала искать пропущенные значения ушло только 8 часов.

Я считаю, что не успел сделать предобработку данных. Думаю, мне ещё 5 часов нужно на доделку.\
На вводную часть можно даже не смотреть, он сплошь черновой.

Я старался делать проект, рассказывая историю, свои мысли. Не знаю, насколько это практично.\
Но думаю, что всё делаю правильно.

Буду рад послушать, что скажет твой опытный взгляд!\
Может есть вариант проще что-то сделать.\
Может мои функции-портянки полная чушь :)\
Короче, жги!

Касаемо автомобилей, тема очень мне интересна.\
Есть несколько Excel документов, куда я вручную заносил инфу по автомобилям.\
В идеале я бы лучше сам спарсил подобную информацию по авторынку за последние 7 лет, провёл очистку и анализ данных.\
Но парсингом не владею, пока что.

Ладно, утомил уже)

<br>

<br>

# Анализ продаж автомобилей в Казахстане

ПРОТОТИП:

Мы имеем агрегированные данные по авторынку — дан датасет с продажами автомобилей в Казахстане за $2019$ год в период с января по сентябрь.

**Цель проекта:** определить рыночные сегменты `Меркур Авто` и разработать маркетинговый план.

**Задачи и план действий:**

1. Обзор данных
2. Предобработка данных
3. Исследовательский анализ данных:
   1. **Провести анализ рынка** (поделить на коммерческий и некоммерческий транспорт):
      * Емкость рынка автомобилей: в денежном и количественном выражении;
      * Марки лидеры на рынке автомобилей;
      * Динамика рынка: общая, по сегментам;
      * RFM-анализ моделей авто (показатели Frequency и Monetary);
      * Продажи автомобилей в разрезе бренд / сегмент;
      * Продажи по маркам;
      * Продажи по регионам;
      * Проверить гипотезу: стоимость автомобиля зависит от уровня развития региона (средней заработной платы по региону);
      * Продажи автоцентров;
      * Модели-лидеры на рынке.
      
   2. **Анализ положения Меркур Авто:**
      * Выручка: общая, по маркам, средняя, ежемесячная, ежемесячная по маркам;
      * Продажи по регионам: общие, по маркам;
      * Конкурентный анализ;
      * BCG анализ (анализ продаж по моделям).

<br>

## Обзор данных

Сначала импортируем нужные библиотеки.

In [1]:
# импорт библиотек
import pandas as pd
import numpy as np

Прочитаем csv файл.

In [2]:
# чтение файла
df = pd.read_csv('https://raw.githubusercontent.com/SweexFox/portfolio-projects/main/python-projects/7-kz-car-market/auto_kz_2019.csv', sep=';')

Посмотрим первые строки.

In [3]:
df

Год     Месяц     Компания  Бренд  Модель   Модификация Год выпуска  \
0      2019       Май  Mercur Auto   Audi      A3          TFSI        2018   
1      2019    Август  Mercur Auto   Audi      A3          TFSI        2018   
2      2019    Апрель  Mercur Auto   Audi      A4          TFSI        2018   
3      2019      Июль  Mercur Auto   Audi      A4          TFSI        2018   
4      2019      Июль  Mercur Auto   Audi      A4          TFSI        2018   
...     ...       ...          ...    ...     ...           ...         ...   
39961  2019  Сентябрь     ТК КАМАЗ  KAMAZ  58815Z  KAMAZ 58815Z        2019   
39962  2019  Сентябрь     ТК КАМАЗ  KAMAZ  58815Z  KAMAZ 58815Z        2019   
39963  2019  Сентябрь     ТК КАМАЗ  KAMAZ  58815Z  KAMAZ 58815Z        2019   
39964  2019  Сентябрь     ТК КАМАЗ  KAMAZ  58815Z  KAMAZ 58815Z        2019   
39965  2019  Сентябрь     ТК КАМАЗ  KAMAZ  58815Z  KAMAZ 58815Z        2019   

       Страна-производитель Вид топлива Объём двиг, л,  ... Тип клиента  \
0                  Германия      Бензин            1,4  ...   Физ. Лицо   
1                  Германия      Бензин            1,4  ...    Юр. Лицо   
2                  Германия      Бензин            1,4  ...   Физ. Лицо   
3                  Германия      Бензин            1,4  ...    Юр. Лицо   
4                  Германия      Бензин            1,4  ...   Физ. Лицо   
...                     ...         ...            ...  ...         ...   
39961  Республика Казахстан      Дизель            NaN  ...    Юр. Лицо   
39962  Республика Казахстан      Дизель            NaN  ...    Юр. Лицо   
39963  Республика Казахстан      Дизель            NaN  ...    Юр. Лицо   
39964  Республика Казахстан      Дизель            NaN  ...    Юр. Лицо   
39965  Республика Казахстан      Дизель            NaN  ...    Юр. Лицо   

      Форма расчета Количество    Цена, USD Продажа, USD              Область  \
0       безналичный        1.0        28115        28115             г.Алматы   
1          наличный        1.0     32246,99     32246,99             г.Алматы   
2       безналичный        1.0        32000        32000             г.Алматы   
3       безналичный        1.0        31929        31929             г.Алматы   
4          наличный        1.0        31929        31929             г.Алматы   
...             ...        ...          ...          ...                  ...   
39961   Безналичная        1.0  48756,92071  48756,92071  Актюбинская область   
39962   Безналичная        1.0  48756,92071  48756,92071  Актюбинская область   
39963   Безналичная        1.0  48756,92071  48756,92071  Актюбинская область   
39964   Безналичная        1.0  48756,92071  48756,92071  Актюбинская область   
39965   Безналичная        1.0  48756,92071  48756,92071  Актюбинская область   

              Сегментация 2013                 Класс 2013 Сегментация Eng  \
0          Легковые автомобили                    C класс               C   
1          Легковые автомобили                    C класс               C   
2          Легковые автомобили                    D класс               D   
3          Легковые автомобили                    D класс               D   
4          Легковые автомобили                    D класс               D   
...                        ...                        ...             ...   
39961  Коммерческие автомобили  Крупнотоннажные грузовики               O   
39962  Коммерческие автомобили  Крупнотоннажные грузовики               O   
39963  Коммерческие автомобили  Крупнотоннажные грузовики               O   
39964  Коммерческие автомобили  Крупнотоннажные грузовики               O   
39965  Коммерческие автомобили  Крупнотоннажные грузовики               O   

      Локализация производства  
0                       Импорт  
1                       Импорт  
2                       Импорт  
3                       Импорт  
4                       Импорт  
...                        ...  
39961   Локальное производств

Что сразу бросается в глаза, так это отсутствие первичных ключей в таблице, данные обезличены.

<br>

Все колонки не влезли в обзор. Нужно снять лимит, чтобы такого не случилось в будущем.

In [4]:
pd.set_option('display.max_columns', None)

<br>

Посмотрим сводную информацию о таблице.

In [5]:
# общая информация
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39966 entries, 0 to 39965
Data columns (total 25 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Год                             39966 non-null  int64  
 1   Месяц                           39966 non-null  object 
 2   Компания                        39966 non-null  object 
 3   Бренд                           39966 non-null  object 
 4   Модель                          39966 non-null  object 
 5   Модификация                     36375 non-null  object 
 6   Год выпуска                     39465 non-null  object 
 7   Страна-производитель            39966 non-null  object 
 8   Вид топлива                     36826 non-null  object 
 9   Объём двиг, л,                  35708 non-null  object 
 10  Коробка передач                 36711 non-null  object 
 11  Тип привода                     35677 non-null  object 
 12  Сегмент                         

<br>

Выведем размер таблицы.

In [6]:
# размер таблицы
df.shape

(39966, 25)

Мы имеем $25$ колонок и $39966$ строк.

<br>

Вот список с названиями колонок, где есть пропуски.

In [7]:
# колонки с пропусками
df.columns[df.isna().any()]

Index(['Модификация', 'Год выпуска', 'Вид топлива', 'Объём двиг, л,',
       'Коробка передач', 'Тип привода', 'Сегмент', 'Тип клиента',
       'Форма расчета', 'Количество'],
      dtype='object')

<br>

Выведем типы данных колонок.

In [8]:
df.dtypes

Год                                 int64
Месяц                              object
Компания                           object
Бренд                              object
Модель                             object
Модификация                        object
Год выпуска                        object
Страна-производитель               object
Вид топлива                        object
Объём двиг, л,                     object
Коробка передач                    object
Тип привода                        object
Сегмент                            object
Регион                             object
Наименование дилерского центра     object
Тип клиента                        object
Форма расчета                      object
Количество                        float64
Цена, USD                          object
Продажа, USD                       object
Область                            object
Сегментация 2013                   object
Класс 2013                         object
Сегментация Eng                   

<br>

### Обзор колонок

Чтобы понять, всё ли в порядке с типами данных в таблице, нужно разобрать каждую колонку.\
В этом нам поможет документация, где дано описание каждой колонки.

`Год` – год продажи.

In [9]:
df['Год'].value_counts(dropna=False)

2019    39966
Name: Год, dtype: int64

Имеем одно значение, `2019` год, как и было указано во введении. Тип данных верный. 

<br>

`Месяц` – месяц продажи.

In [10]:
df['Месяц'].value_counts(dropna=False)

Июль        5930
Сентябрь    5312
Август      4812
Май         4798
Июнь        4754
Апрель      4177
Март        3662
Январь      3384
Февраль     3137
Name: Месяц, dtype: int64

Имеем значения с январь по сентябрь, как и было указано во введении. Тип данных верный.

<br>

`Компания` – название автоцентра.

In [11]:
df['Компания'].value_counts(dropna=False)

Toyota Motor Kazakhstan          11951
Astana Motors                     7395
БИПЭК АВТО                        3624
Вираж                             2909
Astana Motors                     2774
Allur Auto                        2526
Renault Россия                    1796
Nissan Manufacturing RUS          1149
Равон Моторс Казахстан             947
ТК КАМАЗ                           893
Mercur Auto                        639
Ravon Motors Kazakstan             559
Subaru Kazakhstan                  503
ММС Рус                            408
Лифан Моторс Рус                   233
Автоцентр-Бавария                  224
СВС-ТРАНС                          202
Hyundai Com Trans Kazakhstan       155
УзАвто-Казахстан                   152
Автомир ГК                         112
Volkswagen Group Rus               109
Eurasia Motor Premium              102
Almaty Motors Premium               94
СемАЗ                               93
Autokapital                         85
TERRA MOTORS             

Видны неявные дубликаты. Тип данных верный.

<br>

`Бренд` – название продаваемой марки автомобиля.

In [12]:
df['Бренд'].value_counts(dropna=False)

Toyota                  10745
Hyundai                 10168
Jac                      1991
Lada                     1969
GAZ                      1821
Renault                  1796
Ravon                    1794
Lexus                    1206
Nissan                   1053
UAZ                       927
KAMAZ                     892
Kia                       832
Volkswagen                750
Chevrolet                 635
Subaru                    504
Mitsubishi                410
Skoda                     379
ANKAI                     300
Lifan                     233
BMW                       209
Isuzu                     198
Hyundai Truck & Bus       155
Land Rover                135
Mazda                     112
Infiniti                   96
Mercedes-Benz              94
Cadillac                   72
Audi                       52
Porsche                    52
Yutong                     44
Shacman                    43
Volvo                      42
Hino                       41
Jaguar    

Тип данных верный.

<br>

`Модель` – название модели автомобиля.

In [13]:
df['Модель'].value_counts(dropna=False)

Camry           4853
Tucson          3271
Accent          2211
Elantra         2062
Creta           1775
                ... 
F-Type             1
4320-1951-60       1
Fiesta             1
HD 170             1
4311               1
Name: Модель, Length: 273, dtype: int64

Тип данных верный.

<br>

`Модификация` – модификация модели автомобиля.

In [14]:
df['Модификация'].value_counts(dropna=False)

NaN                                                   3591
B5                                                    1470
BX                                                    1210
54                                                    1007
Hyundai Elantra AD FL Active                           764
                                                      ... 
QX50 19MY 2.0L PURE                                      1
H350 BUS 16+1                                            1
City                                                     1
Scania R-Series крупнотоннажные грузовики R440B6x2       1
GAZ  СемАЗ 330202 грузовой 1,5т                          1
Name: Модификация, Length: 1384, dtype: int64

Тип данных верный. Но в комментариях документации нам предлагают избавиться от этой колонки.

<br>

`Год выпуска` – год производства автомобиля.

In [15]:
df['Год выпуска'].value_counts(dropna=False)

2019     29185
2018      8679
2 019      841
NaN        501
2 018      402
2017       324
2016        30
2014         2
2013         1
2011         1
Name: Год выпуска, dtype: int64

Тип данных неверный. Нужно поменять на `int`.\
Также видны неявные дубликаты.

<br>

`Страна-производитель` – страна, где произведён автомобиль.

In [16]:
df['Страна-производитель'].value_counts(dropna=False)

Республика Казахстан    19369
Российская Федерация    12846
Япония                   4595
Турция                   1167
Таиланд                   970
США                       289
Германия                  265
UK                        197
Китай                      94
Узбекистан                 70
Австрия                    33
Швеция                     18
Корея                      17
Нидерланды                 12
Испания                     9
Бельгия                     6
Польша                      6
Венгрия                     2
Белоруссия                  1
Name: Страна-производитель, dtype: int64

Тип данных верный.

<br>

`Вид топлива` – бензин, дизель, электричество, гибрид.

In [17]:
df['Вид топлива'].value_counts(dropna=False)

Бензин           34801
NaN               3140
Дизель            1762
бензин             159
дизель              41
2                   23
1,6                 14
Электричество       10
гибрид              10
Электро              3
0                    3
Name: Вид топлива, dtype: int64

Тип данных верный.\
Но видны неявные дубликаты и аномальные значения. Нужно разобраться.

<br>

`Объём двиг, л,` – объем двигателя автомобиля в литрах.

In [18]:
df['Объём двиг, л,'].value_counts(dropna=False)

1,6     5337
2       5097
NaN     4258
2,7     3394
2.5     2641
        ... 
25,7       1
15,7       1
4,3,       1
7,7        1
2,9        1
Name: Объём двиг, л,, Length: 115, dtype: int64

Здесь неверный тип данных.\
Видны аномальные значения.

<br>

`Коробка передач` – тип коробки переключения передач.

In [19]:
df['Коробка передач'].value_counts(dropna=False)

AT             11379
6 AT            8842
MT              3297
NaN             3255
CVT             2100
               ...  
7 АКПП PDK         1
8 AT               1
12AT               1
12АТ               1
8-ступ АКПП        1
Name: Коробка передач, Length: 84, dtype: int64

Тип данных верный.

<br>

`Тип привода` – тип привода автомобиля.

In [20]:
df['Тип привода'].value_counts(dropna=False)

4WD              9412
2 WD             5078
2WD              4678
FF               4578
NaN              4289
Передний         3270
4 WD             2607
Полный           1917
Задний           1469
FWD               995
AWD               962
RWD               205
Передний (FF)     136
0                 116
передний           56
quattro            47
4х2                38
4Motion            26
4x4                22
4х4                18
4x2                16
4х2.2              10
4X4                 6
полный              5
#Н/Д                4
4X2                 4
Астана              2
Name: Тип привода, dtype: int64

Тип данных верный.\
Но видны неявные дубликаты и аномальные значения.

<br>

`Сегмент` – сегмент, к которому относится авто.

In [21]:
df['Сегмент'].value_counts(dropna=False)

NaN                               6761
D класс                           4368
C-SUV                             3484
Компактные SUV                    2603
B                                 2211
                                  ... 
5 door                               1
sedan                                1
Промтоварный фургон Т25 с б.д.       1
Sportcar                             1
борт                                 1
Name: Сегмент, Length: 120, dtype: int64

Тип данных верный.\
Видны аномальные значения.\
Также в комментариях к документации нам нам предлагают избавиться от этой колонки.

<br>

`Регион` – это город продажи.\
Проверить это можно, сверясь с этим [списком](https://ru.wikipedia.org/wiki/Список_городов_Казахстана_по_численности_населения).

In [22]:
df['Регион'].value_counts(dropna=False)

Алматы              11179
Нур-Султан           8244
Шымкент              2880
Костанай             2447
Атырау               2162
Караганда            2076
ЭКСПОРТ              1810
Актау                1495
Уральск              1493
Актобе               1351
Павлодар             1214
Усть-Каменогорск     1160
Кызылорда             554
Петропавловск         508
Кокшетау              471
Семей                 290
Талдыкорган           230
Тараз                 205
Экибастуз              88
Рудный                 47
Каскелен               38
Туркестан              15
Сарыагаш                4
Кульсары                2
Риддер                  2
Зыряновск               1
Name: Регион, dtype: int64

Тип данных верный.

<br>

`Наименование дилерского центра` – название автоцентра.

In [23]:
df['Наименование дилерского центра'].value_counts(dropna=False)

Hyundai Premium Almaty     1600
Hyundai Auto Almaty        1425
Hyundai Premium Astana     1385
Тойота Центр Алматы        1343
Тойота Центр Астана        1333
                           ... 
СарыаркаАвтоПром              1
КВЦ-АВТО Караганда            1
Allur Auto Taraz              1
Меридиан АВТО Караганда       1
Автотрейд К                   1
Name: Наименование дилерского центра, Length: 205, dtype: int64

Тип данных верный.\
Но в комментариях к документации нам предлагают избавиться от этой колонки, так как она дублирует колонку `Компания`.

<br>

`Тип клиента` – юридическое или физическое лицо.

In [24]:
df['Тип клиента'].value_counts(dropna=False)

Физ. Лицо       24568
Юр. Лицо         7873
NaN              7047
Корп. клиент      161
ФизЛицо           132
юридическое        97
ЮрЛицо             30
физ.лицо           29
Юр.Лицо            25
физическое          4
Name: Тип клиента, dtype: int64

Тип данных верный.\
Видны неявные дубликаты.\
Нам предлагают удалить эту колонку, так как для анализа это некритично.

<br>

`Форма расчета` – наличный и безналичный расчет.

In [25]:
df['Форма расчета'].value_counts(dropna=False)

NaN                                         25928
кредит                                       6190
безналичный                                  4276
Безналичная                                  1335
Собственные средства                          698
наличный                                      599
Наличная                                      499
Безналичная                                   204
Акция Собственные средства (Trade in 5%)       78
нал                                            58
trade-in                                       35
Перечисление                                   21
б/н                                             8
Без оплаты                                      8
Отсрочка платежа                                6
наличные                                        6
перечислением                                   6
Без.Наличный                                    5
лизинг                                          2
безналичный                                     2


Тип данных верный.\
Видны неявные дубликаты.\
Предложено удалить эту колонку, так как много пропусков.

<br>

`Количество` – количество автомобилей в заказе.

In [26]:
df['Количество'].value_counts(dropna=False)

 1.0      37203
 2.0       1017
 3.0        452
 4.0        282
 5.0        185
 6.0        120
 7.0        100
 8.0         79
 10.0        63
 9.0         61
 12.0        45
 13.0        36
 11.0        35
 14.0        33
 15.0        26
 18.0        24
 16.0        23
 17.0        18
 20.0        15
 19.0        14
 22.0        12
 24.0        12
 23.0        12
 21.0        11
 25.0         9
 26.0         9
 30.0         9
 32.0         6
 NaN          6
 29.0         6
 50.0         5
 27.0         4
 28.0         3
 33.0         3
 31.0         3
 36.0         3
 62.0         2
 43.0         1
 70.0         1
 35.0         1
 60.0         1
 66.0         1
 42.0         1
-1.0          1
 115.0        1
 54.0         1
 100.0        1
 79.0         1
 47.0         1
 34.0         1
 41.0         1
 38.0         1
 63.0         1
 46.0         1
 37.0         1
 51.0         1
 40.0         1
Name: Количество, dtype: int64

Тип данных неверный.\
Возможно, есть аномалия.

<br>

`Цена, USD` – цена автомобиля.

In [27]:
df['Цена, USD'].value_counts(dropna=False)

9884,695773    559
11600          531
13800          428
12819,73695    412
9893,925137    402
              ... 
33414,8476       1
31757,19357      1
13046,91369      1
47398,60939      1
35340,96699      1
Name: Цена, USD, Length: 3510, dtype: int64

Тип данных неверный.

<br>

`Продажа, USD` – цена заказа (цена авто, умноженная на количество, за вычетом скидок, если есть)

In [28]:
df['Продажа, USD'].value_counts(dropna=False)

9884,695773    559
12819,73695    412
9893,925137    402
9969,169424    315
13800          230
              ... 
13173,59905      1
252390,7719      1
13305,33504      1
14045,64021      1
35340,96699      1
Name: Продажа, USD, Length: 4183, dtype: int64

Тип данных неверный.

<br>

`Область` – область Казахстана, где продан автомобиль.

In [29]:
df['Область'].value_counts(dropna=False)

г.Алматы                          11179
г.Нур-Султан                       8244
Южно-Казахстанская область         2880
Костанайская область               2494
Атырауская область                 2164
Карагандинская область             2076
Экспорт область                    1810
Мангистауская область              1495
Западно-Казахстанская область      1493
Восточно-Казахстанская область     1453
Актюбинская область                1351
Павлодарская область               1302
Кызылординская область              554
Северо-Казахстанская область        508
Акмолинская область                 471
Алматинская область                 268
Жамбылская область                  205
Туркестанская область                19
Name: Область, dtype: int64

Тип данных верный.

<br>

`Сегментация 2013` – категории автомобилей.

In [30]:
df['Сегментация 2013'].value_counts(dropna=False)

Внедорожники               17928
Легковые автомобили        16333
Коммерческие автомобили     4329
Пикапы                       974
Минивэны                     402
Name: Сегментация 2013, dtype: int64

Тип данных верный.

<br>

`Класс 2013` – классификация автомобилей.

In [31]:
df['Класс 2013'].value_counts(dropna=False)

B класс                      7028
Компактные SUV               6593
D класс                      5385
Субкомпактные SUV            5339
Среднеразмерные SUV          3994
C класс                      3584
Полноразмерные SUV           2002
Малотоннажные грузовики      1940
Крупнотоннажные грузовики    1034
Pick-ups                      974
Микроавтобусы                 433
Компактвэн                    354
Развозные автомобили          352
Большие автобусы              321
E класс                       244
Среднетоннажные грузовики     192
Средние автобусы               57
Полноразмерный Минивэн         48
A класс                        42
F класс                        40
Спортивные автомобили          10
Name: Класс 2013, dtype: int64

Тип данных верный.

<br>

`Сегментация Eng` – английская сегментация.

In [32]:
df['Сегментация Eng'].value_counts(dropna=False)

K1    11932
B      7028
D      5385
K2     3994
C      3584
K3     2002
N      1940
O      1591
K4      974
L1      429
M       402
L2      369
E       244
A        42
F        40
G2       10
Name: Сегментация Eng, dtype: int64

Тип данных верный.\
Нам предложено избавиться от этой колонки.

<br>

`Локализация производства` – автомобиль домашнего или зарубежного производства.

In [33]:
df['Локализация производства'].value_counts(dropna=False)

Импорт                    20597
Локальное производство    19369
Name: Локализация производства, dtype: int64

Тип данных верный.\
Нам предложено избавиться от этой колонки.

<br>

Итак, в документации приложены комментарии.\
В них нам предлагают избавиться от следующих колонок:
* `Модификация`
* `Сегмент`
* `Наименование дилерского центра` — дублирует колонку `Компания`.
* `Тип клиента` — в рамках анализа некритично.
* `Форма расчета` — много пропусков.
* `Сегментация Eng`
* `Локализация производства` — дублирует колонку `Страна-производитель`.

Но мы сами решим, что с ними делать.

<br>

Были обнаружены неверные типы данных в следующих колонках:
1. Год выпуска (`object` преобразовать в `int`)
2. Объём двиг, л, (`object` преобразовать в `float`)
3. Количество (`float` преобразовать в `int`)
4. Цена, USD (`object` преобразовать в `int`)
5. Продажа, USD (`object` преобразовать в `int`)

<br>

Пожалуй, с обзором данных закончили. Пора приступить к их предобработке.

<br>

## Предобработка данных

### Удаление ненужных колонок

Решим, какие колонки нам не нужны. 

Однозначно можно избавиться от полей `Модификация` и `Сегментация Eng`, потому что эта информация действительно мало чего несёт.

In [34]:
df.drop(columns=['Модификация', 'Сегментация Eng'], inplace=True)

<br>

Под вопросом стоят следующие колонки:
* `Сегмент` и `Класс 2013`. Они похожи, их нужно сравнить.
* `Наименование дилерского центра`. Она похожа на колонку `Компания`. Нужно сравнить их.
* `Форма расчёта`. Много пропусков. Нужно посмотреть эти пропуски.
* `Сегментация 2013`. С ней нужно глубже разобраться.

<br>

Напишем функцию, показывающую данные колонок.

In [35]:
def column_data(column):
    print(column.value_counts(dropna=False).head(20))
    print('')
    print(f'Количество уникальных значений: {column.nunique()}')
    print('')
    print(f'Список первых 50 уникальных значений: {column.sort_values().unique()[:50]}')

<br>

Итак, **сравнение `Сегмент` и `Класс 2013`**.

In [36]:
column_data(df['Сегмент'])

NaN                            6761
D класс                        4368
C-SUV                          3484
Компактные SUV                 2603
B                              2211
C                              2062
B класс                        1735
Среднеразмерные SUV            1715
B-SUV                          1562
C класс                        1338
Грузовой автомобиль             892
Полноразмерные SUV              808
Пикапы                          778
Среднеразмерные SUV Premium     663
D-SUV                           639
Внедорожники                    617
D класс                         573
Легковые автомобили             547
SUV cars                        504
легковой                        380
Name: Сегмент, dtype: int64

Количество уникальных значений: 119

Список первых 50 уникальных значений: ['#Н/Д' '0' '16+1' '43+1' '5 door' '5 doors' '5doors' 'A класс' 'A класс '
 'ASTER Auto' 'Ambulance' 'B' 'B класс' 'B класс ' 'B-SUV' 'Bus' 'C'
 'C класс' 'C класс ' 'C-SUV' 'C

In [37]:
column_data(df['Класс 2013'])

B класс                      7028
Компактные SUV               6593
D класс                      5385
Субкомпактные SUV            5339
Среднеразмерные SUV          3994
C класс                      3584
Полноразмерные SUV           2002
Малотоннажные грузовики      1940
Крупнотоннажные грузовики    1034
Pick-ups                      974
Микроавтобусы                 433
Компактвэн                    354
Развозные автомобили          352
Большие автобусы              321
E класс                       244
Среднетоннажные грузовики     192
Средние автобусы               57
Полноразмерный Минивэн         48
A класс                        42
F класс                        40
Name: Класс 2013, dtype: int64

Количество уникальных значений: 21

Список первых 50 уникальных значений: ['A класс' 'B класс' 'C класс' 'D класс' 'E класс' 'F класс' 'Pick-ups'
 'Большие автобусы' 'Компактвэн' 'Компактные SUV'
 'Крупнотоннажные грузовики' 'Малотоннажные грузовики' 'Микроавтобусы'
 'Полноразмерные SUV'

В общем, в колонке `Сегмент` много мусорных значений, колонка `Класс 2013` значительно привлекательнее.\
**Сносим первую.**

<br>

**Сравнение `Наименование дилерского центра` и `Компания`**.

In [38]:
column_data(df['Наименование дилерского центра'])

Hyundai Premium Almaty     1600
Hyundai Auto Almaty        1425
Hyundai Premium Astana     1385
Тойота Центр Алматы        1343
Тойота Центр Астана        1333
Toyota City Астана         1319
Toyota City                1258
Тойота Центр Жетысу        1150
HYUNDAI AUTO ASTANA        1117
Allur Auto Almaty          1079
ЭКСПОРТ                     773
Hyundai Center Shimkent     768
Тойота Центр Шымкент        750
Автомир-Центр Караганда     707
Тойота Центр Атырау         634
Caspi Auto Атырау           569
ASTER AUTO Алматы           554
Тойота Центр Костанай       542
Лексус Астана               519
БИПЭК АВТО Астана           492
Name: Наименование дилерского центра, dtype: int64

Количество уникальных значений: 205

Список первых 50 уникальных значений: ['ABS-INVEST' 'ALAN MOTORS' 'ALAN MOTORS\xa0Усть-Каменогорск'
 'AST-commerce' 'ASTER AUTO CЕМЕЙ' 'ASTER AUTO Алматы'
 'ASTER AUTO Шымкент' 'Aktobe Hyundai Motors' 'Alan Motors Trade'
 'Allur Auto Almaty' 'Allur Auto Astana' 'Allur Au

In [39]:
column_data(df['Компания'])

Toyota Motor Kazakhstan          11951
Astana Motors                     7395
БИПЭК АВТО                        3624
Вираж                             2909
Astana Motors                     2774
Allur Auto                        2526
Renault Россия                    1796
Nissan Manufacturing RUS          1149
Равон Моторс Казахстан             947
ТК КАМАЗ                           893
Mercur Auto                        639
Ravon Motors Kazakstan             559
Subaru Kazakhstan                  503
ММС Рус                            408
Лифан Моторс Рус                   233
Автоцентр-Бавария                  224
СВС-ТРАНС                          202
Hyundai Com Trans Kazakhstan       155
УзАвто-Казахстан                   152
Автомир ГК                         112
Name: Компания, dtype: int64

Количество уникальных значений: 40

Список первых 50 уникальных значений: ['Allur Auto' 'Almaty Motors Premium' 'Astana Motors' 'Astana Motors '
 'Autokapital' 'Caspian Motors' 'Daewoo Bus K

In [40]:
df.pivot_table(index=['Компания', 'Наименование дилерского центра'], aggfunc='size')\
  .reset_index()\
  .sort_values(by=0, ascending=False)\
  .reset_index(drop=True)\
  .rename(columns={0: 'Кол-во покупок'})\
  .head(20)

Компания Наименование дилерского центра  Кол-во покупок
0   Toyota Motor Kazakhstan            Тойота Центр Алматы            1343
1   Toyota Motor Kazakhstan            Тойота Центр Астана            1333
2   Toyota Motor Kazakhstan             Toyota City Астана            1317
3   Toyota Motor Kazakhstan                    Toyota City            1258
4             Astana Motors         Hyundai Premium Almaty            1211
5   Toyota Motor Kazakhstan            Тойота Центр Жетысу            1150
6             Astana Motors         Hyundai Premium Astana            1025
7                Allur Auto              Allur Auto Almaty             950
8             Astana Motors            Hyundai Auto Almaty             892
9             Astana Motors            HYUNDAI AUTO ASTANA             860
10               Allur Auto                        ЭКСПОРТ             768
11  Toyota Motor Kazakhstan           Тойота Центр Шымкент             750
12  Toyota Motor Kazakhstan            Тойота Центр Атырау             634
13            Astana Motors        Hyundai Center Shimkent             544
14  Toyota Motor Kazakhstan          Тойота Центр Костанай             542
15  Toyota Motor Kazakhstan                  Лексус Астана             519
16               БИПЭК АВТО              БИПЭК АВТО Астана             492
17  Toyota Motor Kazakhstan                  Лексус Алматы             474
18                    Вираж                   Вираж Алматы             453
19              Mercur Auto             Mercur Auto Алматы             427

Думаю, **стоит оставить обе колонки.** У одной компании может быть несколько дилерских центров. Почему бы не оставить эту информацию.

<br>

**Смотрим `Форма расчета`.**

In [41]:
column_data(df['Форма расчета'])

NaN                                         25928
кредит                                       6190
безналичный                                  4276
Безналичная                                  1335
Собственные средства                          698
наличный                                      599
Наличная                                      499
Безналичная                                   204
Акция Собственные средства (Trade in 5%)       78
нал                                            58
trade-in                                       35
Перечисление                                   21
б/н                                             8
Без оплаты                                      8
Отсрочка платежа                                6
наличные                                        6
перечислением                                   6
Без.Наличный                                    5
лизинг                                          2
безналичный                                     2


In [42]:
print(f'Процент пропущенных значений в колонке `Форма расчета`: {round(df["Форма расчета"].isna().mean() * 100)}')

Процент пропущенных значений в колонке `Форма расчета`: 65


Довольно большой процент пропусков, с которыми ничего не поделаешь.\
Но всё равно не хочется избавляться от колонки. **Оставим её.**

<br>

**Смотрим `Сегментация 2013`.**

In [43]:
column_data(df['Сегментация 2013'])

Внедорожники               17928
Легковые автомобили        16333
Коммерческие автомобили     4329
Пикапы                       974
Минивэны                     402
Name: Сегментация 2013, dtype: int64

Количество уникальных значений: 5

Список первых 50 уникальных значений: ['Внедорожники' 'Коммерческие автомобили' 'Легковые автомобили' 'Минивэны'
 'Пикапы']


Данную категоризацию также не хочется убирать из таблицы. **Оставим эту колонку.**

<br>

Таким образом, **сносим только одну мусорную колонку — `Сегмент`.**

In [44]:
# удаление поля
df.drop(columns='Сегмент', inplace=True)

<br>

### Переименование колонок

Нужно привести все колонки к единому стилю, переименовав их.

Вот их список.

In [45]:
df.columns

Index(['Год', 'Месяц', 'Компания', 'Бренд', 'Модель', 'Год выпуска',
       'Страна-производитель', 'Вид топлива', 'Объём двиг, л,',
       'Коробка передач', 'Тип привода', 'Регион',
       'Наименование дилерского центра', 'Тип клиента', 'Форма расчета',
       'Количество', 'Цена, USD', 'Продажа, USD', 'Область',
       'Сегментация 2013', 'Класс 2013', 'Локализация производства'],
      dtype='object')

In [46]:
# переименование колонок
df = df.rename(columns={'Год': 'year',
                        'Месяц': 'month',
                        'Компания': 'company',
                        'Модель': 'model',
                        'Бренд': 'brand',
                        'Год выпуска': 'manufacturing_year',
                        'Страна-производитель': 'manufacturing_country',
                        'Вид топлива': 'fuel_type',
                        'Объём двиг, л,': 'engine_displacement_l',
                        'Коробка передач': 'transmission_type',
                        'Тип привода': 'drive_type',
                        'Регион': 'city',
                        'Наименование дилерского центра': 'dealer_center_name',
                        'Тип клиента': 'customer_type',
                        'Форма расчета': 'payment_form',
                        'Количество': 'quantity',
                        'Цена, USD': 'price_usd',
                        'Продажа, USD': 'sale_usd',
                        'Область': 'region',
                        'Сегментация 2013': 'car_type',
                        'Класс 2013': 'car_classification',
                        'Локализация производства': 'assembly_type'})

<br>

Можно задать иной, более логичный порядок колонкам в таблице.

In [47]:
df = df[['year',
         'month',
         'company',
         'car_type',
         'brand',
         'model',
         'car_classification',
         'manufacturing_year',
         'assembly_type',
         'manufacturing_country',
         'fuel_type',
         'engine_displacement_l',
         'transmission_type',
         'drive_type',
         'region',
         'city',
         'dealer_center_name',
         'customer_type',
         'payment_form',
         'quantity',
         'price_usd',
         'sale_usd']]

<br>

### Замена типов данных колонок

Теперь нужно поменять типы данных в колонках, где они неверны.

Вот колонки и их типы данных.

In [48]:
df.dtypes

year                       int64
month                     object
company                   object
car_type                  object
brand                     object
model                     object
car_classification        object
manufacturing_year        object
assembly_type             object
manufacturing_country     object
fuel_type                 object
engine_displacement_l     object
transmission_type         object
drive_type                object
region                    object
city                      object
dealer_center_name        object
customer_type             object
payment_form              object
quantity                 float64
price_usd                 object
sale_usd                  object
dtype: object

**Где неверные типы данных:**
1. `manufacturing_year` — `object` преобразовать в `int`.
2. `engine_displacement_l` — `object` преобразовать в `float`.
3. `quantity` — `float` преобразовать в `int`.
4. `price_usd` — `object` преобразовать в `int`.
5. `sale_usd` — `object` преобразовать в `int`.

<br>

Преобразуем `manufacturing_year`.

Посмотрим сначала уникальные значения внутри.

In [49]:
df['manufacturing_year'].sort_values().unique()

array(['2011', '2013', '2014', '2016', '2017', '2018', '2019', '2\xa0018',
       '2\xa0019', nan], dtype=object)

Странные символы `2\xa0` — результат работы кодировки.\
Они скрывают неявные дубликаты, они не дадут преобразовать строку в целочисленный формат.\
Избавимся от этих дублей, убьём сразу двух зайцев.

In [50]:
# устранение дублей
df['manufacturing_year'] = df['manufacturing_year'].replace('2\xa0018', '2018')\
                                                   .replace('2\xa0019', '2019')

In [51]:
# проверка
df['manufacturing_year'].sort_values().unique()

array(['2011', '2013', '2014', '2016', '2017', '2018', '2019', nan],
      dtype=object)

Дубли устранились.

Поменяем тип данных.

In [52]:
# смена типа данных
df['manufacturing_year'] = pd.to_numeric(df['manufacturing_year'], errors='coerce').astype('Int64')

In [53]:
# проверка
df['manufacturing_year'].dtypes

Int64Dtype()

Всё верно.

<br>

Преобразуем `engine_displacement_l`.

Посмотрим сначала уникальные значения внутри.

In [54]:
print(df['engine_displacement_l'].sort_values().unique())
print('')
print(f'Количество уникальных значений: {df["engine_displacement_l"].nunique()}')

['#Н/Д' '0' '1,2' '1,248' '1,2T' '1,33' '1,4' '1,4 Turbo' '1,485' '1,5'
 '1,591' '1,596' '1,598' '1,6' '1,6 MPI' '1,6 T-GDI' '1,69' '1,7' '1,774'
 '1,8' '1,998' '1,999' '1.5' '1.6' '10,5' '10,7' '11' '11,7' '12' '12,3'
 '12,7' '12,8' '13' '13,7' '14,7' '15,7' '16,7' '17,7' '18,7' '19,7' '2'
 '2,0' '2,0 CRDI' '2,0 MPI' '2,2' '2,359' '2,4' '2,4 GDI' '2,4 MPI' '2,4G'
 '2,5' '2,5 CRDI VGT' '2,5 CRDI WGT' '2,693' '2,7' '2,8' '2,9' '2.0'
 '2.0h' '2.4G' '2.5' '2.7' '2.7 ' '2.8' '20,7' '21,7' '22,7' '23,7' '24,7'
 '25,7' '26,7' '3' '3,0 L' '3,342' '3,47' '3,5' '3,6' '3,7' '3,8' '3,9'
 '3.5' '3.8' '4' '4,3' '4,3,' '4,4' '4,6' '4,7' '4,9' '4,98' '4,98 L,'
 '4.0' '4.6' '400 Л.С.' '5' '5,2' '5,5' '5,6' '5,7' '5.7' '6,2' '6,5'
 '6,6' '6,7' '6,7L' '7,5' '7,6' '7,7' '8,4 L,' '8,7' '88 KWH' '9,7' 'AT'
 'MT' nan]

Количество уникальных значений: 114


Непорядок. Запятые в объёме двигателя нужно поменять на точки, а от всех буквенных значений нужно избавиться. Иначе не сможем преобразовать во `float`.

In [55]:
# замена запятых на точки
df['engine_displacement_l'] = df['engine_displacement_l'].str.replace(',', '.')\
                                                         .str.replace('[^0-9.]', '', regex=True)

<br>

Посмотрим, что поменялось.

In [56]:
print(df['engine_displacement_l'].sort_values().unique())
print('')
print(f'Количество уникальных значений: {df["engine_displacement_l"].nunique()}')

['' '0' '1.2' '1.248' '1.33' '1.4' '1.485' '1.5' '1.591' '1.596' '1.598'
 '1.6' '1.69' '1.7' '1.774' '1.8' '1.998' '1.999' '10.5' '10.7' '11'
 '11.7' '12' '12.3' '12.7' '12.8' '13' '13.7' '14.7' '15.7' '16.7' '17.7'
 '18.7' '19.7' '2' '2.0' '2.2' '2.359' '2.4' '2.5' '2.693' '2.7' '2.8'
 '2.9' '20.7' '21.7' '22.7' '23.7' '24.7' '25.7' '26.7' '3' '3.0' '3.342'
 '3.47' '3.5' '3.6' '3.7' '3.8' '3.9' '4' '4.0' '4.3' '4.3.' '4.4' '4.6'
 '4.7' '4.9' '4.98' '4.98.' '400..' '5' '5.2' '5.5' '5.6' '5.7' '6.2'
 '6.5' '6.6' '6.7' '7.5' '7.6' '7.7' '8.4.' '8.7' '88' '9.7' nan]

Количество уникальных значений: 87


Диапазон уникальных значений уменьшился.\
Значения, которые состояли полностью из букв, поменялись на пустые значения. Их нужно будет поменять на пропуски.\
В некоторых значениях появились лишние точки. Нужно тоже исправить.

In [57]:
df['engine_displacement_l'] = df['engine_displacement_l'].replace('4.3.', '4.3')\
                                                         .replace('4.98.', '4.98')\
                                                         .replace('400..', '400')\
                                                         .replace('8.4.', '8.4')\
                                                         .replace('', np.nan)

Наконец, поменяем тип данных.

In [58]:
# смена типа данных
df['engine_displacement_l'] = df['engine_displacement_l'].astype('float')

In [59]:
# проверка
df['engine_displacement_l'].dtypes

dtype('float64')

Всё верно.

<br>

Преобразуем `quantity`.

Посмотрим сначала уникальные значения внутри.

In [60]:
print(df['quantity'].sort_values().unique())
print('')
print(f'Количество уникальных значений: {df["quantity"].nunique()}')

[ -1.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.
  14.  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.
  28.  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  40.  41.  42.
  43.  46.  47.  50.  51.  54.  60.  62.  63.  66.  70.  79. 100. 115.
  nan]

Количество уникальных значений: 56


Здесь всё просто. Меняем тип данных.

In [61]:
# замена типа данных
df['quantity'] = df['quantity'].astype('Int64')

In [62]:
# проверка
df['quantity'].dtypes

Int64Dtype()

Всё верно.

<br>

Преобразуем `price_usd`.

Посмотрим сначала уникальные значения внутри.

In [63]:
print(df['price_usd'].sort_values().unique())
print('')
print(f'Количество уникальных значений: {df["price_usd"].nunique()}')

['100056,4835' '10015,24362' '100216,6313' ... '99467,01183' '9969,169424'
 '99767,25773']

Количество уникальных значений: 3510


Здесь с максимальной точностью указана цена автомобиля. Но эта ловля центов нам не нужна. Нужно округлить просто округлить цену.\
Чтобы преобразовать тип данных, нужно заменить разделение дробной части от целого с запятой на точку.

In [64]:
# замена символов
df['price_usd'] = df['price_usd'].str.replace(',', '.')

Затем строчный тип преобразуем в вещественный.

In [65]:
# str > float
df['price_usd'] = df['price_usd'].astype('float')

Затем округлим цену автомобиля в большую сторону.

In [66]:
# округление
df['price_usd'] = df['price_usd'].round()

Наконец, преобразуем вещественный тип в целочисленный.

In [67]:
# float > int
df['price_usd'] = df['price_usd'].astype('Int64')

In [68]:
# проверка
df['price_usd'].dtypes

Int64Dtype()

Всё верно.

<br>

Преобразуем `sale_usd`.

Посмотрим сначала уникальные значения внутри.

In [69]:
print(df['sale_usd'].sort_values().unique())
print('')
print(f'Количество уникальных значений: {df["sale_usd"].nunique()}')

['-35588,25' '0' '100000' ... '9969,169424' '99766,70464' '99767,25773']

Количество уникальных значений: 4183


Напомню, что это цена автомобиля, умноженная на их количество, за вычетом скидок.

Опять же имеем максимально точную стоимость "заказа". Это нам ни к чему.\
Процесс преобразования такой же, как и в `price_usd`:\
заменим запятую на точку > строчный преобразуем в вещественный > округлим > вещественный преобразуем в целочисленный.

In [70]:
# замена символов
df['sale_usd'] = df['sale_usd'].str.replace(',', '.')

# str > float
df['sale_usd'] = df['sale_usd'].astype('float')

# округление 
df['sale_usd'] = df['sale_usd'].round()

# float > int
df['sale_usd'] = df['sale_usd'].astype('Int64')

# проверка
df['sale_usd'].dtypes

Int64Dtype()

Тип данных поменялся.

<br>

Таким образом, мы поменяли тип данных в следующих колонках:
1. `manufacturing_year`
2. `engine_displacement_l`
3. `quantity`
4. `price_usd`
5. `sale_usd`

<br>

### "Олицетворение" данных

Как было уже упомянуто, данные в таблице обезличены, не хватает первичных ключей.\
Если мы произведём проверку на явные дубликаты, мы обнаружим очень большое их количество.\
Это такие дубликаты-строки, которые повторяются в полном объёме: мы можем обнаружить абсолютно одинаковые строки.\
Допустим, сейчас выведу строку-клон, у которой уже есть точно такая же строка в таблице.

In [71]:
df[df.duplicated()].head(1)

year month      company             car_type brand model  \
8  2019  Июнь  Mercur Auto  Легковые автомобили  Audi    A6   

  car_classification  manufacturing_year assembly_type manufacturing_country  \
8            E класс                2019        Импорт              Германия   

  fuel_type  engine_displacement_l transmission_type drive_type    region  \
8    Бензин                    3.0          S-tronic    quattro  г.Алматы   

     city  dealer_center_name customer_type payment_form  quantity  price_usd  \
8  Алматы  Mercur Auto Алматы     Физ. Лицо     наличный         1      78940   

   sale_usd  
8     78940

In [72]:
print(f'Количество явных (полных) дубликатов: {df.duplicated().sum()}')
print(f'Процент явных (полных) дубликатов: {round(df.duplicated().sum() / len(df) * 100, 1)}%')

Количество явных (полных) дубликатов: 20197
Процент явных (полных) дубликатов: 50.5%


Удаление их будет серьёзной ошибкой.\
Здесь просто нужно добавить уникальный идентификатор каждой строке, и всё наладится.

<br>

Но перед этим **зададим сортировку сначала по календарному месяцу, затем по бренду, и затем по модели.**

In [73]:
# определение порядка месяцев
month_order = ['Январь', 'Февраль', 'Март', 'Апрель','Май', 'Июнь', 'Июль', 'Август', 'Сентябрь']

# преобразование в категориальный тип данных с заданным порядком
df['month'] = pd.Categorical(df['month'], categories=month_order, ordered=True)

# сортировка по месяцу, бренду, модели
df = df.sort_values(by=['month', 'brand', 'model'])

<br>

Теперь прилепим уникальный ID к каждой строке.

In [74]:
# олицетворение строк
df = df.reset_index(drop=True)\
       .reset_index()\
       .rename(columns={'index': 'id'})

<br>

Теперь проверим, что с явными дубликатами.

In [75]:
print(f'Количество явных (полных) дубликатов: {df.duplicated().sum()}')
print(f'Процент явных (полных) дубликатов: {round(df.duplicated().sum() / len(df) * 100, 1)}%')

Количество явных (полных) дубликатов: 0
Процент явных (полных) дубликатов: 0.0%


Их нет.\
Конечно, данный способ неидеален. Потому что, в теории, один клиент может зайти в разные месяцы и купить автомобиль снова.\
Но это будет очень состоятельный покупатель и такое явление очень большая редкость. Получается, что это клиент с одним и тем же ID.\
Но это совсем незначительная трудность.

<br>

### Дубликаты и аномалии

Проблему явных дубликатов мы исправили.\
Теперь нужно разобраться с неявными дубликатами и аномальными значениями.\
Для этого пройдёмся по каждой колонке.

<br>

Создадим функцию для анализа колонки.

In [76]:
def duplicates(column):
    print(df[column].value_counts(dropna=False).head(10))
    print('')
    print(f'Количество непропущенных значений: {df[column].count()}')
    print(f'Количество уникальных значений: {df[column].nunique()}')
    print('')
    print(f'Первые 50 уникальных значений в алфавитном порядке:')
    print(df[column].sort_values().unique()[:50])

<br>

`ID`

In [77]:
duplicates('id')

0        1
35492    1
25241    1
31386    1
29339    1
19100    1
17053    1
23198    1
21151    1
33445    1
Name: id, dtype: int64

Количество непропущенных значений: 39966
Количество уникальных значений: 39966

Первые 50 уникальных значений в алфавитном порядке:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


Ранее каждой строке мы поставили уникальный ID.\
Дубликатов и аномалий нет.

<br>

`Год`

In [78]:
duplicates('year')

2019    39966
Name: year, dtype: int64

Количество непропущенных значений: 39966
Количество уникальных значений: 1

Первые 50 уникальных значений в алфавитном порядке:
[2019]


Все строки показывают $2019$ год, как положено.\
Дубликатов и аномалий нет.

<br>

`Месяц`

In [79]:
duplicates('month')

Июль        5930
Сентябрь    5312
Август      4812
Май         4798
Июнь        4754
Апрель      4177
Март        3662
Январь      3384
Февраль     3137
Name: month, dtype: int64

Количество непропущенных значений: 39966
Количество уникальных значений: 9

Первые 50 уникальных значений в алфавитном порядке:
['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь']
Categories (9, object): ['Январь' < 'Февраль' < 'Март' < 'Апрель' ... 'Июнь' < 'Июль' < 'Август' < 'Сентябрь']


Все месяцы с января по сентябрь есть.\
Дубликатов и аномалий нет.

<br>

`Компания`

In [80]:
duplicates('company')

Toyota Motor Kazakhstan     11951
Astana Motors                7395
БИПЭК АВТО                   3624
Вираж                        2909
Astana Motors                2774
Allur Auto                   2526
Renault Россия               1796
Nissan Manufacturing RUS     1149
Равон Моторс Казахстан        947
ТК КАМАЗ                      893
Name: company, dtype: int64

Количество непропущенных значений: 39966
Количество уникальных значений: 40

Первые 50 уникальных значений в алфавитном порядке:
['Allur Auto' 'Almaty Motors Premium' 'Astana Motors' 'Astana Motors '
 'Autokapital' 'Caspian Motors' 'Daewoo Bus Kazakhstan'
 'Eurasia Motor Premium' 'Hino Motors ' 'Hyundai Com Trans Kazakhstan '
 'MAN Truck & Bus Kazakhstan' 'MMC RUS' 'Mercur Auto' 'Mercur Autos'
 'Nissan Manufacturing RUS' 'Ravon Motors Kazakstan' 'Renault Россия'
 'Scandinavian Motors' 'Scania Central Asia' 'Subaru Kazakhstan'
 'TERRA MOTORS' 'Toyota Motor Kazakhstan' 'Volkswagen Group Rus'
 'Автодом Motors KST' 'Автокапитал

Выведем полное распределение значений колонки.\
Это поможет найти выбивающиеся значения.

In [81]:
df['company'].value_counts()

Toyota Motor Kazakhstan          11951
Astana Motors                     7395
БИПЭК АВТО                        3624
Вираж                             2909
Astana Motors                     2774
Allur Auto                        2526
Renault Россия                    1796
Nissan Manufacturing RUS          1149
Равон Моторс Казахстан             947
ТК КАМАЗ                           893
Mercur Auto                        639
Ravon Motors Kazakstan             559
Subaru Kazakhstan                  503
ММС Рус                            408
Лифан Моторс Рус                   233
Автоцентр-Бавария                  224
СВС-ТРАНС                          202
Hyundai Com Trans Kazakhstan       155
УзАвто-Казахстан                   152
Автомир ГК                         112
Volkswagen Group Rus               109
Eurasia Motor Premium              102
Almaty Motors Premium               94
СемАЗ                               93
Autokapital                         85
TERRA MOTORS             

Не без помощи поисковых систем замечены неявные дубликаты. Устраним их.

In [82]:
# неявные дубликаты
df['company'] = df['company'].replace('Каспиан Моторс', 'Caspian Motors')\
                             .replace('Astana Motors ', 'Astana Motors')\
                             .replace('Хино Моторс Казахстан', 'Hino Motors')\
                             .replace('MMC RUS', 'ММС Рус')\
                             .replace('Mercur Autos', 'Mercur Auto')\
                             .replace('Равон Моторс Казахстан', 'Ravon Motors Kazakstan')\
                             .replace('Автокапитал', 'Autokapital')\
                             .replace('Автомир ГК', 'Автомир-Центр')

# неточности в названиях
df['company'] = df['company'].replace('Hino Motors ', 'Hino Motors')\
                             .replace('ТОО "Eurasia Motor Zhaik"', 'Eurasia Motor Zhaik')

Посмотрим снова картину.

In [83]:
duplicates('company')

Toyota Motor Kazakhstan     11951
Astana Motors               10169
БИПЭК АВТО                   3624
Вираж                        2909
Allur Auto                   2526
Renault Россия               1796
Ravon Motors Kazakstan       1506
Nissan Manufacturing RUS     1149
ТК КАМАЗ                      893
Mercur Auto                   643
Name: company, dtype: int64

Количество непропущенных значений: 39966
Количество уникальных значений: 32

Первые 50 уникальных значений в алфавитном порядке:
['Allur Auto' 'Almaty Motors Premium' 'Astana Motors' 'Autokapital'
 'Caspian Motors' 'Daewoo Bus Kazakhstan' 'Eurasia Motor Premium'
 'Eurasia Motor Zhaik' 'Hino Motors' 'Hyundai Com Trans Kazakhstan '
 'MAN Truck & Bus Kazakhstan' 'Mercur Auto' 'Nissan Manufacturing RUS'
 'Ravon Motors Kazakstan' 'Renault Россия' 'Scandinavian Motors'
 'Scania Central Asia' 'Subaru Kazakhstan' 'TERRA MOTORS'
 'Toyota Motor Kazakhstan' 'Volkswagen Group Rus' 'Автодом Motors KST'
 'Автомир-Центр' 'Автоцентр-Бавари

Теперь стало на $8$ уникальных значений меньше. Дубли устранились.

<br>

`Тип автомобиля`

In [84]:
duplicates('car_type')

Внедорожники               17928
Легковые автомобили        16333
Коммерческие автомобили     4329
Пикапы                       974
Минивэны                     402
Name: car_type, dtype: int64

Количество непропущенных значений: 39966
Количество уникальных значений: 5

Первые 50 уникальных значений в алфавитном порядке:
['Внедорожники' 'Коммерческие автомобили' 'Легковые автомобили' 'Минивэны'
 'Пикапы']


Здесь всё интересно намешано.

**Внедорожники** — это легковые или полугрузовые автомобили повышенной проходимости и повышенного комфорта в салоне. По-другому их можно назвать кроссоверами.\
**Легковые автомобили** — это тип автомобиля, которые имеют различные кузова: седан, хэтчбек, универсал, лифтбек, кабриолет, купе\
**Коммерческие автомобили** — это автомобили, используемые в коммерческих целях: грузовики, автобусы и прочее.
**Пикапы** — это внедорожники, которые могут быть как грузовыми, так и легковыми.\
**Минивэны** — это тип кузова легковых автомобилей с тремя рядами сидений.

Здесь стоит **пикапы перенести во внедорожники, а минивэны в легковые.**

In [85]:
df['car_type'] = df['car_type'].replace('Пикапы', 'Внедорожники')\
                               .replace('Минивэны', 'Легковые автомобили')

Проверим снова.

In [86]:
duplicates('car_type')

Внедорожники               18902
Легковые автомобили        16735
Коммерческие автомобили     4329
Name: car_type, dtype: int64

Количество непропущенных значений: 39966
Количество уникальных значений: 3

Первые 50 уникальных значений в алфавитном порядке:
['Внедорожники' 'Коммерческие автомобили' 'Легковые автомобили']


Теперь порядок.

<br>

`Марка автомобиля`

In [87]:
duplicates('brand')

Toyota     10745
Hyundai    10168
Jac         1991
Lada        1969
GAZ         1821
Renault     1796
Ravon       1794
Lexus       1206
Nissan      1053
UAZ          927
Name: brand, dtype: int64

Количество непропущенных значений: 39966
Количество уникальных значений: 46

Первые 50 уникальных значений в алфавитном порядке:
['ANKAI' 'Audi' 'BMW' 'Cadillac' 'Chevrolet' 'Daewoo' 'Dong Feng' 'Ford'
 'Foton' 'GAZ' 'Hino' 'Hyundai' 'Hyundai Truck & Bus' 'Infiniti' 'Isuzu'
 'Iveco' 'Jac' 'Jaguar' 'KAMAZ' 'Kia' 'Lada' 'Land Rover' 'Lexus' 'Lifan'
 'MAN' 'Mazda' 'Mercedes-Benz' 'Mercedes-Benz Trucks' 'Mini' 'Mitsubishi'
 'Nefaz' 'Nissan' 'Peugeot' 'Porsche' 'Ravon' 'Renault' 'Scania' 'Shacman'
 'Skoda' 'Subaru' 'Toyota' 'UAZ' 'Volkswagen' 'Volvo' 'Yutong' 'Урал']


Здесь всё в норме. Дублей и аномалий нет.

<br>

`Модель автомобиля`

In [88]:
duplicates('model')

Camry       4853
Tucson      3271
Accent      2211
Elantra     2062
Creta       1775
LC Prado    1711
Nexia R3    1699
S3          1286
RAV4        1213
Corolla     1089
Name: model, dtype: int64

Количество непропущенных значений: 39966
Количество уникальных значений: 273

Первые 50 уникальных значений в алфавитном порядке:
['2206' '2217' '2310' '2705' '2752' '3' '3 серия' '300' '301' '3151'
 '3221' '32551' '3302' '3303' '3308' '3309' '3741' '3909' '3962' '4308'
 '4311' '43118' '4320' '4320-1951-40' '4320-1951-60' '43253' '43502'
 '44108' '45141' '45142' '45143' '4x4' '5 серия' '500' '5299' '53215'
 '53504' '53605' '54115' '5490' '5557' '58815Z' '6' '6 серия' '65111'
 '65115' '65116' '65117' '6520' '65206']


<br>

Нужно сделать сводную таблицу по бренду и моделям, чтобы было удобнее разобраться.

In [89]:
pd.set_option('display.max_rows', None)
df.pivot_table(index=['brand', 'model'], aggfunc='size').reset_index(name='orders')

pd.reset_option('display.max_rows', None)
df.pivot_table(index=['brand', 'model'], aggfunc='size').reset_index(name='orders')

brand          model  orders
0    ANKAI        HF-D105      30
1    ANKAI  HFF6124G03EV3      10
2    ANKAI    HFF6127GZ-4      20
3    ANKAI       HFF6850G     240
4     Audi             A3       2
..     ...            ...     ...
270   Урал          32551       1
271   Урал           4320       7
272   Урал   4320-1951-40       1
273   Урал   4320-1951-60       1
274   Урал           5557       2

[275 rows x 3 columns]

Здесь всё выглядит в порядке.\
Неявных дубликатов и аномалий не видно.

<br>

`Классификация автомобиля`

In [90]:
duplicates('car_classification')

B класс                      7028
Компактные SUV               6593
D класс                      5385
Субкомпактные SUV            5339
Среднеразмерные SUV          3994
C класс                      3584
Полноразмерные SUV           2002
Малотоннажные грузовики      1940
Крупнотоннажные грузовики    1034
Pick-ups                      974
Name: car_classification, dtype: int64

Количество непропущенных значений: 39966
Количество уникальных значений: 21

Первые 50 уникальных значений в алфавитном порядке:
['A класс' 'B класс' 'C класс' 'D класс' 'E класс' 'F класс' 'Pick-ups'
 'Большие автобусы' 'Компактвэн' 'Компактные SUV'
 'Крупнотоннажные грузовики' 'Малотоннажные грузовики' 'Микроавтобусы'
 'Полноразмерные SUV' 'Полноразмерный Минивэн' 'Развозные автомобили'
 'Спортивные автомобили' 'Среднеразмерные SUV' 'Среднетоннажные грузовики'
 'Средние автобусы' 'Субкомпактные SUV']


Здесь всё аккуратно. Дублей и аномалий нет.

<br>

`Год производства автомобиля`

In [91]:
duplicates('manufacturing_year')

2019    30026
2018     9081
NaN       501
2017      324
2016       30
2014        2
2011        1
2013        1
Name: manufacturing_year, dtype: Int64

Количество непропущенных значений: 39465
Количество уникальных значений: 7

Первые 50 уникальных значений в алфавитном порядке:
<IntegerArray>
[2011, 2013, 2014, 2016, 2017, 2018, 2019, <NA>]
Length: 8, dtype: Int64


Кажется, здесь всё в порядке. Один автомобиль был даже произведён в $2011$ году. Ничего особого.

<br>

`Где собран автомобиль`

In [92]:
duplicates('assembly_type')

Импорт                    20597
Локальное производство    19369
Name: assembly_type, dtype: int64

Количество непропущенных значений: 39966
Количество уникальных значений: 2

Первые 50 уникальных значений в алфавитном порядке:
['Импорт' 'Локальное производство']


Всё в порядке. Есть местная сборка, есть зарубежная сборка.\
Можно проверить это следующим кодом. Результат должен быть таким же, какой выдаёт `Локальное производство`.

In [93]:
len(df[df['manufacturing_country'] == 'Республика Казахстан'])

19369

Сделано в Казахстане, значит локальное производство.

<br>

`Страна сборки`

In [94]:
duplicates('manufacturing_country')

Республика Казахстан    19369
Российская Федерация    12846
Япония                   4595
Турция                   1167
Таиланд                   970
США                       289
Германия                  265
UK                        197
Китай                      94
Узбекистан                 70
Name: manufacturing_country, dtype: int64

Количество непропущенных значений: 39966
Количество уникальных значений: 19

Первые 50 уникальных значений в алфавитном порядке:
['UK' 'Австрия' 'Белоруссия' 'Бельгия' 'Венгрия' 'Германия' 'Испания'
 'Китай' 'Корея' 'Нидерланды' 'Польша' 'Республика Казахстан'
 'Российская Федерация' 'США' 'Таиланд' 'Турция' 'Узбекистан' 'Швеция'
 'Япония']


Здесь всё в норме.

<br>

`Тип топлива`

In [95]:
duplicates('fuel_type')

Бензин           34801
NaN               3140
Дизель            1762
бензин             159
дизель              41
2                   23
1,6                 14
Электричество       10
гибрид              10
Электро              3
Name: fuel_type, dtype: int64

Количество непропущенных значений: 36826
Количество уникальных значений: 10

Первые 50 уникальных значений в алфавитном порядке:
['0' '1,6' '2' 'Бензин' 'Дизель' 'Электричество' 'Электро' 'бензин '
 'гибрид' 'дизель ' nan]


Здесь нужно привести значения к нужному регистру, а также убрать пробелы, так мы избавимся от дублей.\
Также тут затесались объёмы двигателей, это аномальные значения, их нужно заменить.

In [96]:
df.query('fuel_type == "2" or fuel_type == "1,6" or fuel_type == "0"').head(10)

id  year   month         company      car_type    brand   model  \
1898  1898  2019  Январь  Renault Россия  Внедорожники  Renault  Duster   
1899  1899  2019  Январь  Renault Россия  Внедорожники  Renault  Duster   
1900  1900  2019  Январь  Renault Россия  Внедорожники  Renault  Duster   
1901  1901  2019  Январь  Renault Россия  Внедорожники  Renault  Duster   
1902  1902  2019  Январь  Renault Россия  Внедорожники  Renault  Duster   
1903  1903  2019  Январь  Renault Россия  Внедорожники  Renault  Duster   
1904  1904  2019  Январь  Renault Россия  Внедорожники  Renault  Duster   
1905  1905  2019  Январь  Renault Россия  Внедорожники  Renault  Duster   
1906  1906  2019  Январь  Renault Россия  Внедорожники  Renault  Duster   
1907  1907  2019  Январь  Renault Россия  Внедорожники  Renault  Duster   

     car_classification  manufacturing_year assembly_type  \
1898  Субкомпактные SUV                2019        Импорт   
1899  Субкомпактные SUV                2018        Импорт   
1900  Субкомпактные SUV                2018        Импорт   
1901  Субкомпактные SUV                2018        Импорт   
1902  Субкомпактные SUV                2018        Импорт   
1903  Субкомпактные SUV                2018        Импорт   
1904  Субкомпактные SUV                2018        Импорт   
1905  Субкомпактные SUV                2018        Импорт   
1906  Субкомпактные SUV                2018        Импорт   
1907  Субкомпактные SUV                2018        Импорт   

     manufacturing_country fuel_type  engine_displacement_l transmission_type  \
1898  Российская Федерация         2                    NaN               4WD   
1899  Российская Федерация         2                    NaN               4WD   
1900  Российская Федерация         2                    NaN               4WD   
1901  Российская Федерация         2                    NaN               4WD   
1902  Российская Федерация         2                    NaN               4WD   
1903  Российская Федерация       1,6                    NaN               4WD   
1904  Российская Федерация         2                    NaN               4WD   
1905  Российская Федерация         2                    NaN               4WD   
1906  Российская Федерация         2                    NaN               4WD   
1907  Российская Федерация         2                    NaN               4WD   

     drive_type                         region        city  \
1898        4WD  Западно-Казахстанская область     Уральск   
1899        4WD                   г.Нур-Султан  Нур-Султан   
1900        4WD                   г.Нур-Султан  Нур-Султан   
1901        4WD         Кызылординская область   Кызылорда   
1902        4WD         Карагандинская область   Караганда   
1903        4WD         Карагандинская область   Караганда   
1904        4WD         Карагандинская область   Караганда   
1905        4WD         Карагандинская область   Караганда   
1906        4WD         Карагандинская область   Караганда   
1907        4WD         Карагандинская область   Караганда   

           dealer_center_name customer_type payment_form  quantity  price_usd  \
1898           Урал-Кров Авто           NaN          NaN         1      12250   
1899     Кристалл Авто Астана           NaN          NaN         1      12250   
1900     Кристалл Авто Астана           NaN          NaN         1      12250   
1901  Кристалл Авто Кызылорда           NaN          NaN         1      12250   
1902  Кристалл Авто Караганда           NaN          NaN         1      12250   
1903  Кристалл Авто Караганда           NaN          NaN         1      12250   
1904  Кристалл Авто Караганда           NaN          NaN         1      12250   
1905  Кристалл Авто Караганда           NaN          NaN         1      12250   
1906  Кристалл Авто Караганда           NaN          NaN         1      12250   
1907  Кристалл Авто Караганда           NaN          NaN         1      12250   

      sale_usd  
1898     12250  
1899     

Эти числа являются объёмом двигателей, это подтвердит автомобильный интернет портал, их нужно перенести в другую колонку.\
Также выяснил, что тип топлива — бензин должен быть.

<br>

Переместим значения.

In [97]:
# срез
fuel_mist = df.query('fuel_type == "2" or fuel_type == "1,6"')

# замена символов
fuel_mist = fuel_mist['fuel_type'].str.replace(',', '.')

# преобразование в float
fuel_mist = fuel_mist.astype('float')

# перемещение в engine_displacement_l
df.loc[fuel_mist.index, 'engine_displacement_l'] = fuel_mist

<br>

Приведём символы к нужному регистру.

In [98]:
# регистр
df['fuel_type'] = df['fuel_type'].str.capitalize()

# устранение пробелов и аномальных значений
df['fuel_type'] = df['fuel_type'].str.replace(' ', '')\
                                 .replace('Электро', 'Электричество')\
                                 .replace('2', 'Бензин')\
                                 .replace('1,6', 'Бензин')\
                                 .replace('0', 'Бензин')

<br>

Проверим, что изменилось.

In [99]:
duplicates('fuel_type')

Бензин           35000
NaN               3140
Дизель            1803
Электричество       13
Гибрид              10
Name: fuel_type, dtype: int64

Количество непропущенных значений: 36826
Количество уникальных значений: 4

Первые 50 уникальных значений в алфавитном порядке:
['Бензин' 'Гибрид' 'Дизель' 'Электричество' nan]


Теперь порядок. Аномалии и дубли устранены.

<br>

`Объём двигателя`

In [100]:
duplicates('engine_displacement_l')

2.000    7934
1.600    7778
2.500    5034
2.700    4669
NaN      4262
1.500    1423
1.596    1120
2.400    1103
4.600     754
3.500     705
Name: engine_displacement_l, dtype: int64

Количество непропущенных значений: 35704
Количество уникальных значений: 80

Первые 50 уникальных значений в алфавитном порядке:
[1.2   1.248 1.33  1.4   1.485 1.5   1.591 1.596 1.598 1.6   1.69  1.7
 1.774 1.8   1.998 1.999 2.    2.2   2.359 2.4   2.5   2.693 2.7   2.8
 2.9   3.    3.342 3.47  3.5   3.6   3.7   3.8   3.9   4.    4.3   4.4
 4.6   4.7   4.9   4.98  5.    5.2   5.5   5.6   5.7   6.2   6.5   6.6
 6.7   7.5  ]


Когда мы меняли тип данных в этой колонке, мы хорошо предобработали её. Но она до сих пор не в идеальном состоянии.\
Среди значений видим такие, где есть сотые и тысячные доли. Скорее всего, это так перевели кубические сантиметры в литры. **Всё нужно округлить до десятых.**

In [101]:
# округление
df['engine_displacement_l'] = df['engine_displacement_l'].round(1)

<br>

Насколько я помню, были аномалии. Нужно отсортировать уникальные значения в обратном порядке и посмотреть их.

In [102]:
df['engine_displacement_l'].sort_values(ascending=False).unique()

array([400. ,  88. ,  26.7,  25.7,  24.7,  23.7,  22.7,  21.7,  20.7,
        19.7,  18.7,  17.7,  16.7,  15.7,  14.7,  13.7,  13. ,  12.8,
        12.7,  12.3,  12. ,  11.7,  11. ,  10.7,  10.5,   9.7,   8.7,
         8.4,   7.7,   7.6,   7.5,   6.7,   6.6,   6.5,   6.2,   5.7,
         5.6,   5.5,   5.2,   5. ,   4.9,   4.7,   4.6,   4.4,   4.3,
         4. ,   3.9,   3.8,   3.7,   3.6,   3.5,   3.3,   3. ,   2.9,
         2.8,   2.7,   2.5,   2.4,   2.2,   2. ,   1.8,   1.7,   1.6,
         1.5,   1.4,   1.3,   1.2,   nan])

Сложно представить себе автомобиль с объёмом двигателя больше $10$ литров.\
Можно разобрать автомобили с такими значениями.

In [103]:
# авто с двигателями более 10 л
df[df['engine_displacement_l'] >= 10].sort_values(by='engine_displacement_l', ascending=False).head()

id  year    month                company                 car_type  \
11754  11754  2019   Апрель  Almaty Motors Premium             Внедорожники   
4471    4471  2019  Февраль  Almaty Motors Premium             Внедорожники   
21118  21118  2019     Июнь  Almaty Motors Premium             Внедорожники   
23917  23917  2019     Июль             Allur Auto  Коммерческие автомобили   
23919  23919  2019     Июль             Allur Auto  Коммерческие автомобили   

        brand          model car_classification  manufacturing_year  \
11754  Jaguar         I-Pace     Компактные SUV                2019   
4471   Jaguar         I-Pace     Компактные SUV                2019   
21118  Jaguar         I-Pace     Компактные SUV                2019   
23917   ANKAI  HFF6124G03EV3   Большие автобусы                2019   
23919   ANKAI  HFF6124G03EV3   Большие автобусы                2019   

                assembly_type manufacturing_country      fuel_type  \
11754                  Импорт                    UK  Электричество   
4471                   Импорт                    UK  Электричество   
21118                  Импорт                    UK  Электричество   
23917  Локальное производство  Республика Казахстан  Электричество   
23919  Локальное производство  Республика Казахстан  Электричество   

       engine_displacement_l transmission_type drive_type  \
11754                  400.0          РЕДУКТОР        4WD   
4471                   400.0          РЕДУКТОР        4WD   
21118                  400.0          РЕДУКТОР        4WD   
23917                   88.0               NaN        2WD   
23919                   88.0               NaN        2WD   

                     region      city     dealer_center_name customer_type  \
11754              г.Алматы    Алматы  Almaty Motors Premium     Физ. Лицо   
4471               г.Алматы    Алматы  Almaty Motors Premium     Физ. Лицо   
21118              г.Алматы    Алматы  Almaty Motors Premium      Юр. Лицо   
23917  Костанайская область  Костанай      Allur Auto Almaty      Юр. Лицо   
23919  Костанайская область  Костанай      Allur Auto Almaty      Юр. Лицо   

      payment_form  quantity  price_usd  sale_usd  
11754     наличный         1     105389    105389  
4471      наличный         1     117237    117237  
21118  безналичный         1     120413    120413  
23917  безналичный         1     307986    307986  
23919  безналичный         1     307986    307986

В самом верху с объёмом $88$ и выше — это электрокары. И там указана мощность вместо объёма.\
Но у электрокаров нет такого понятия как объём двигателя. У них есть ёмкость батареи.\
Им нужно поставить пропущенные значения.

Нива почувствовала себя супермощной: от $13.7$ до $26.7$ литров значение объёма двигателя. Какой вздор.\
Посмотрим распределение объёмов у всех Нив в датасете.

In [104]:
df[df['model'] == 'Niva']['engine_displacement_l'].value_counts()

1.7     542
2.7       1
21.7      1
14.7      1
8.7       1
16.7      1
5.7       1
7.7       1
25.7      1
26.7      1
22.7      1
10.7      1
11.7      1
20.7      1
18.7      1
13.7      1
23.7      1
12.7      1
9.7       1
24.7      1
3.7       1
17.7      1
15.7      1
6.7       1
4.7       1
19.7      1
Name: engine_displacement_l, dtype: int64

Много неправды. У Шевроле Нивы только один реальный объём: $1.7$ литра.\
Проверено **[здесь](https://www.drom.ru/catalog/chevrolet/niva/g_2009_1658/).** \
Нужно все аномалии заменить здесь модой.

Все остальные транспорты с очень большим объёмом — это или **большие автобусы**, или **крупнотоннажные грузовики**. Что выглядит правдоподобно.

<br>

Итак, заменим показатели мощности двигателя у электрокаров на пропуски.

In [105]:
# замена на пропуски
df.loc[df['fuel_type'] == 'Электричество', 'engine_displacement_l'] = np.NaN

Теперь заменим все значения объёмов двигателя у Нив на модальное (реальное) значение. 

In [106]:
# замена модой
df.loc[df['model'] == 'Niva', 'engine_displacement_l'] = df[df['model'] == 'Niva']['engine_displacement_l'].mode().iloc[0]

Посмотрим распределение нив снова.

In [107]:
df[df['model'] == 'Niva']['engine_displacement_l'].value_counts()

1.7    567
Name: engine_displacement_l, dtype: int64

Отлично. Всё исправлено.

<br>

Посмотрим колонку `engine_displacement_l` ещё раз.

In [108]:
duplicates('engine_displacement_l')

1.6    9075
2.0    8133
2.7    5074
2.5    5034
NaN    4275
1.5    1559
2.4    1247
1.7     833
3.5     788
4.6     754
Name: engine_displacement_l, dtype: int64

Количество непропущенных значений: 35691
Количество уникальных значений: 44

Первые 50 уникальных значений в алфавитном порядке:
[ 1.2  1.3  1.4  1.5  1.6  1.7  1.8  2.   2.2  2.4  2.5  2.7  2.8  2.9
  3.   3.3  3.5  3.6  3.8  3.9  4.   4.3  4.4  4.6  4.9  5.   5.2  5.5
  5.6  5.7  6.2  6.5  6.6  6.7  7.5  7.6  8.4  8.7 10.5 11.  12.  12.3
 12.8 13.   nan]


Количество уникальных значений снизилось с $80$ до $44$. Теперь данные стали значительно чище.

<br>

`Коробка передач`

In [109]:
duplicates('transmission_type')

AT                11379
6 AT               8842
MT                 3297
NaN                3255
CVT                2100
Мех.               2044
CVT (вариатор)     1462
6AT                1166
5МТ                 996
5 МТ                618
Name: transmission_type, dtype: int64

Количество непропущенных значений: 36711
Количество уникальных значений: 83

Первые 50 уникальных значений в алфавитном порядке:
[' 7 АКП' '#Н/Д' '0' '12AT' '12АТ' '4 АТ' '4AT' '4WD' '4АТ' '5 AT' '5 МТ'
 '5AT' '5M' '5MT' '5АТ' '5М' '5МТ' '6 AT' '6 DSG' '6 MT' '6 АТ' '6 МТ'
 '6A' '6AT' '6DSG' '6M/T' '6MT' '6А' '6АТ' '6МТ' '7 DCT' '7 DSG'
 '7 АКПП (PDK)' '7 АКПП PDK' '7AT' '7DCT' '7DSG' '7G-TRONIC' '7АКП' '7АТ'
 '8' '8 AT' '8 АКПП (PDK)' '8 АКПП Tiptronic S' '8 АТ' '8-ступ АКПП' '8A'
 '8AT' '8АКПП' '8АТ']


Полный хаос. $83$ коробок передач.\
Посмотрим их распределение.

In [110]:
pd.set_option('display.max_rows', None)
df['transmission_type'].value_counts(dropna=False)

AT                    11379
6 AT                   8842
MT                     3297
NaN                    3255
CVT                    2100
Мех.                   2044
CVT (вариатор)         1462
6AT                    1166
5МТ                     996
5 МТ                    618
5MT                     614
AMT                     397
6MT                     384
6АТ                     383
6 АТ                    351
АКП                     329
АКПП                    230
CVT(вAриATор)           203
6 MT                    197
8AT                     151
4АТ                     133
АТ                      117
4 АТ                    105
МТ                      104
CVT (вариATор)           92
7DSG                     90
9G-TRONIC                72
6DSG                     71
АT                       61
DSG                      47
8АТ                      46
7 DSG                    42
МКП                      35
8 АТ                     34
МКПП                     34
Tiptronic           

In [111]:
pd.reset_option('display.max_rows')

У автомобилей с двигателями внутреннего сгорания есть всего $4$ коробки переключения передач:
1. Механическая (**MT** — Manual Transmission)
2. Автоматическая (**АТ** — Automatic Transmission)
3. Роботизированная (**АМТ** — Automated Manual Transmission)
4. Вариаторная (**CVT** — Continuously Variable Transmission)

У электрокаров роль трансмиссии выполняет **редуктор**.

Поэтому все $83$ значения колонки нужно привести к этим $5$.

<br>

Сначала можно убрать пробелы и цифры из значений.

In [112]:
df['transmission_type'] = df['transmission_type'].str.replace(' ', '')\
                                                 .str.replace('[0-9]', '', regex=True)

<br>

Посмотрим, что поменялось.

In [113]:
duplicates('transmission_type')

AT               21586
MT                4492
NaN               3255
CVT               2100
Мех.              2044
МТ                1747
CVT(вариатор)     1462
АТ                1182
AMT                397
АКП                338
Name: transmission_type, dtype: int64

Количество непропущенных значений: 36711
Количество уникальных значений: 43

Первые 50 уникальных значений в алфавитном порядке:
['' '#Н/Д' '-ступАКПП' 'A' 'A/T' 'AMT' 'AT' 'CVT' 'CVT(вAриATор)'
 'CVT(вариATор)' 'CVT(вариатор)' 'DCT' 'DSG' 'G-TRONIC' 'M' 'M/T' 'MT'
 'PDK' 'PowershiftS' 'S-Tronic' 'S-tronic' 'Steptronic' 'TDI' 'Tiptronic'
 'WD' 'А' 'А/T' 'АT' 'АКП' 'АКПП' 'АКПП(PDK)' 'АКППPDK' 'АКППTiptronicS'
 'АТ' 'М' 'М/T' 'МT' 'МКП' 'МКПП' 'МТ' 'Мех.' 'Передний' 'РЕДУКТОР' nan]


Значений стало почти в $2$ раза меньше.\
Нужно устранить неявные дубли.

<br>

Преобразуем значения так, чтобы они стали более понятны простому человеку.

Создадим списки, в которых будут дубли определённых коробок передач.

In [114]:
# механическая
mt = ['M', 'M/T', 'MT', 'М', 'М/T', 'МT', 'МКП', 'МКПП', 'МТ', 'Мех.']

# автоматическая
at = ['А', 'А/T', 'АT', 'АКП', 'АКПП', 'АТ', 'G-TRONIC', 'AT', 'A', 'A/T', 'Tiptronic', 'Steptronic', 'АКППTiptronicS', '-ступАКПП']

# робот
amt = ['PDK', 'PowershiftS', 'S-Tronic', 'АКПП(PDK)', 'АКППPDK', 'DCT', 'DSG', 'AMT', 'S-tronic']

# вариатор
cvt = ['CVT', 'CVT(вAриATор)', 'CVT(вариATор)', 'CVT(вариатор)']

# пропуски
nan = ['TDI', 'Передний', '#Н/Д', 'WD', '']

Создадим специальную конструкцию, которая поможет заменить значения.

In [115]:
# каждому значению (ключу) из созданных выше переменных назначено новое одно из пяти значений (значение) 
transmission_mapping = {
    **{value: 'Механическая' for value in mt},
    **{value: 'Автоматическая' for value in at},
    **{value: 'Робот' for value in amt},
    **{value: 'Вариатор' for value in cvt},
    **{value: np.NaN for value in nan}
}
# методу replace передаём словарь, в котором ключи — значения, которые нужно заменить, а значения — соответствующие новые значения
df['transmission_type'] = df['transmission_type'].replace(transmission_mapping)\
                                                 .replace('РЕДУКТОР', 'Редуктор')

Поменяем неточности в коробках передач там, где имеется возможность.

In [116]:
# cayenne
df.loc[df['model'] == 'Cayenne', 'transmission_type'] = 'Автоматическая'
df.loc[df['fuel_type'] == 'Электричество', 'transmission_type'] = 'Редуктор'

<br>

Посмотрим финальный результат.

In [117]:
duplicates('transmission_type')

Автоматическая    23637
Механическая       8409
Вариатор           3857
NaN                3305
Робот               745
Редуктор             13
Name: transmission_type, dtype: int64

Количество непропущенных значений: 36661
Количество уникальных значений: 5

Первые 50 уникальных значений в алфавитном порядке:
['Автоматическая' 'Вариатор' 'Механическая' 'Редуктор' 'Робот' nan]


Теперь в колонке наведён порядок.

<br>

`Тип привода`

In [118]:
duplicates('drive_type')

4WD         9412
2 WD        5078
2WD         4678
FF          4578
NaN         4289
Передний    3270
4 WD        2607
Полный      1917
Задний      1469
FWD          995
Name: drive_type, dtype: int64

Количество непропущенных значений: 35677
Количество уникальных значений: 26

Первые 50 уникальных значений в алфавитном порядке:
['#Н/Д' '0' '2 WD' '2WD' '4 WD' '4Motion' '4WD' '4X2' '4X4' '4x2' '4x4'
 '4х2' '4х2.2' '4х4' 'AWD' 'FF' 'FWD' 'RWD' 'quattro' 'Астана' 'Задний'
 'Передний' 'Передний (FF)' 'Полный' 'передний' 'полный' nan]


Здесь тоже нужно привести всё в порядок.

<br>

Рассмотрим распределение всех значений в колонке.

In [119]:
df['drive_type'].value_counts(dropna=False)

4WD              9412
2 WD             5078
2WD              4678
FF               4578
NaN              4289
Передний         3270
4 WD             2607
Полный           1917
Задний           1469
FWD               995
AWD               962
RWD               205
Передний (FF)     136
0                 116
передний           56
quattro            47
4х2                38
4Motion            26
4x4                22
4х4                18
4x2                16
4х2.2              10
4X4                 6
полный              5
#Н/Д                4
4X2                 4
Астана              2
Name: drive_type, dtype: int64

<br>

Вообще всего существует $4$ вида приводов:
1. Передний (**FWD** — Front Wheel Drive)
2. Задний (**RWD** — Rear Wheel Drive)
3. Полный (**4WD** — Four Wheel Drive)
4. Полный (**AWD** — All Wheel Drive)

<br>

В соответствии с этими приводами нужно привести все значения в колонке.

Создадим списки со значениями, которые нужно заменить на нормальные.

In [120]:
# двухколёсный (2WD)
twd = ['2 WD', '2WD', '4X2', '4x2', '4х2', '4х2.2']

# передний (FWD)
fwd = ['FF', 'FWD', 'Передний', 'Передний (FF)', 'передний']

# задний (RWD)
rwd = ['RWD', 'Задний']

# полный (4WD)
fourwd = ['4WD', '4 WD', '4Motion', '4X4', '4x4', '4х4', 'quattro', 'Полный', 'полный']

# полный (AWD)
awd = ['AWD']

# пропуски
nan = ['#Н/Д', '0', 'Астана']

Создадим конструкцию, которая заменит все неявные дубликаты.

In [121]:
# словарь, ключи которого содержат необработанные значения. Эти необработанные значения будут заменены валидными значенями
drive_type_mapping = {
    **{value: 'Двухколёсный (2WD)' for value in twd},
    **{value: 'Передний (FWD)' for value in fwd},
    **{value: 'Задний (RWD)' for value in rwd},
    **{value: 'Полный (4WD)' for value in fourwd},
    **{value: 'Полный (AWD)' for value in awd},
    **{value: np.NaN for value in nan}
}

# замена значений
df['drive_type'] = df['drive_type'].replace(drive_type_mapping)

<br>

Теперь проверим работу.

In [122]:
duplicates('drive_type')

Полный (4WD)          14060
Двухколёсный (2WD)     9824
Передний (FWD)         9035
NaN                    4411
Задний (RWD)           1674
Полный (AWD)            962
Name: drive_type, dtype: int64

Количество непропущенных значений: 35555
Количество уникальных значений: 5

Первые 50 уникальных значений в алфавитном порядке:
['Двухколёсный (2WD)' 'Задний (RWD)' 'Передний (FWD)' 'Полный (4WD)'
 'Полный (AWD)' nan]


Всё замечательно. Идём дальше.

<br>

`Области Казахстана`

In [123]:
duplicates('region')

г.Алматы                          11179
г.Нур-Султан                       8244
Южно-Казахстанская область         2880
Костанайская область               2494
Атырауская область                 2164
Карагандинская область             2076
Экспорт область                    1810
Мангистауская область              1495
Западно-Казахстанская область      1493
Восточно-Казахстанская область     1453
Name: region, dtype: int64

Количество непропущенных значений: 39966
Количество уникальных значений: 18

Первые 50 уникальных значений в алфавитном порядке:
['Акмолинская область' 'Актюбинская область' 'Алматинская область'
 'Атырауская область' 'Восточно-Казахстанская область'
 'Жамбылская область' 'Западно-Казахстанская область'
 'Карагандинская область' 'Костанайская область' 'Кызылординская область'
 'Мангистауская область' 'Павлодарская область'
 'Северо-Казахстанская область' 'Туркестанская область' 'Экспорт область'
 'Южно-Казахстанская область' 'г.Алматы' 'г.Нур-Султан']


Колонка в полном порядке.

<br>

`Города Казахстана`

In [124]:
duplicates('city')

Алматы        11179
Нур-Султан     8244
Шымкент        2880
Костанай       2447
Атырау         2162
Караганда      2076
ЭКСПОРТ        1810
Актау          1495
Уральск        1493
Актобе         1351
Name: city, dtype: int64

Количество непропущенных значений: 39966
Количество уникальных значений: 26

Первые 50 уникальных значений в алфавитном порядке:
['Актау' 'Актобе' 'Алматы' 'Атырау' 'Зыряновск' 'Караганда' 'Каскелен'
 'Кокшетау' 'Костанай' 'Кульсары' 'Кызылорда' 'Нур-Султан' 'Павлодар'
 'Петропавловск' 'Риддер' 'Рудный' 'Сарыагаш' 'Семей' 'Талдыкорган'
 'Тараз' 'Туркестан' 'Уральск' 'Усть-Каменогорск' 'Шымкент' 'ЭКСПОРТ'
 'Экибастуз']


Колонка в полном порядке.

<br>

`Наименование дилерского центра`

In [125]:
duplicates('dealer_center_name')

Hyundai Premium Almaty    1600
Hyundai Auto Almaty       1425
Hyundai Premium Astana    1385
Тойота Центр Алматы       1343
Тойота Центр Астана       1333
Toyota City Астана        1319
Toyota City               1258
Тойота Центр Жетысу       1150
HYUNDAI AUTO ASTANA       1117
Allur Auto Almaty         1079
Name: dealer_center_name, dtype: int64

Количество непропущенных значений: 39966
Количество уникальных значений: 205

Первые 50 уникальных значений в алфавитном порядке:
['ABS-INVEST' 'ALAN MOTORS' 'ALAN MOTORS\xa0Усть-Каменогорск'
 'AST-commerce' 'ASTER AUTO CЕМЕЙ' 'ASTER AUTO Алматы'
 'ASTER AUTO Шымкент' 'Aktobe Hyundai Motors' 'Alan Motors Trade'
 'Allur Auto Almaty' 'Allur Auto Astana' 'Allur Auto Atyrau '
 'Allur Auto Karaganda' 'Allur Auto Kokshetau' 'Allur Auto Pavlodar '
 'Allur Auto Petropavlovsk ' 'Allur Auto Rus' 'Allur Auto Shymkent '
 'Allur Auto Taraz' 'Allur Auto Ust-Kamenogorsk ' 'Allur Auto Актобе'
 'Allur Auto Костанай' 'Allur Auto Кызылорда' 'Almaty Motors Premi

Здесь всё кажется в порядке. Вижу лишь несколько шероховатостей:
1. Убрать пробелы в конце названий у некоторых центров, например, в `'Allur Auto Petropavlovsk '`.
2. Убрать последствия кодировки `\xa0` в `'ALAN MOTORS\xa0Усть-Каменогорск'`.
3. Убрать $1$ дубль: `'Auto trader'` >> `'Auto Trader'`.

Уберём пробелы.

In [126]:
# используем enumerate для создания кортежа (индекс, значение) для каждого элемента в колонке 'dealer_center_name'
for i, elem in enumerate(df['dealer_center_name']):
    # проверяем, что elem не является пустой строкой или NaN, и последний символ — пробел
    if elem and elem[-1] == ' ':
        # изменяем значение в df: выбираем строку по индексу i, колонку 'dealer_center_name',
        # и устанавливаем новое значение без последнего символа (пробела)
        df.loc[i, 'dealer_center_name'] = elem[:-1]

Уберём `\xa0`.

In [127]:
df['dealer_center_name'] = df['dealer_center_name'].str.replace('\xa0', ' ')

Уберём $1$ дублик.

In [128]:
df['dealer_center_name'] = df['dealer_center_name'].replace('Auto trader', 'Auto Trader')

Как по мне, колонка в полном порядке.

<br>

`Тип покупателя`

In [129]:
duplicates('customer_type')

Физ. Лицо       24568
Юр. Лицо         7873
NaN              7047
Корп. клиент      161
ФизЛицо           132
юридическое        97
ЮрЛицо             30
физ.лицо           29
Юр.Лицо            25
физическое          4
Name: customer_type, dtype: int64

Количество непропущенных значений: 32919
Количество уникальных значений: 9

Первые 50 уникальных значений в алфавитном порядке:
['Корп. клиент' 'Физ. Лицо' 'ФизЛицо' 'Юр. Лицо' 'Юр.Лицо' 'ЮрЛицо'
 'физ.лицо' 'физическое' 'юридическое' nan]


Выходит, есть $3$ типа покупателей:
* Физическое лицо
* Юридическое лицо
* Корпоративный клиент

В соответствии с этими $3$ типами и нужно привести все значения.

In [130]:
df['customer_type'] = df['customer_type'].replace('Физ. Лицо', 'Физическое лицо')\
                                         .replace('ФизЛицо', 'Физическое лицо')\
                                         .replace('физ.лицо', 'Физическое лицо')\
                                         .replace('физическое', 'Физическое лицо')\
                                         .replace('Юр. Лицо', 'Юридическое лицо')\
                                         .replace('Юр.Лицо', 'Юридическое лицо')\
                                         .replace('ЮрЛицо', 'Юридическое лицо')\
                                         .replace('юридическое', 'Юридическое лицо')\
                                         .replace('Корп. клиент', 'Корпоративный клиент')

Проверим.

In [131]:
duplicates('customer_type')

Физическое лицо         24733
Юридическое лицо         8025
NaN                      7047
Корпоративный клиент      161
Name: customer_type, dtype: int64

Количество непропущенных значений: 32919
Количество уникальных значений: 3

Первые 50 уникальных значений в алфавитном порядке:
['Корпоративный клиент' 'Физическое лицо' 'Юридическое лицо' nan]


Всё в порядке.

<br>

`Форма оплаты`

In [132]:
duplicates('payment_form')

NaN                                         25928
кредит                                       6190
безналичный                                  4276
Безналичная                                  1335
Собственные средства                          698
наличный                                      599
Наличная                                      499
Безналичная                                   204
Акция Собственные средства (Trade in 5%)       78
нал                                            58
Name: payment_form, dtype: int64

Количество непропущенных значений: 14038
Количество уникальных значений: 21

Первые 50 уникальных значений в алфавитном порядке:
['trade-in' 'Акция Собственные средства (Trade in 5%)' 'Без оплаты'
 'Без.Наличный' 'Безналичная' 'Безналичная ' 'Наличная' 'Отсрочка платежа'
 'Перечисление' 'Собственные средства' 'б/н' 'безналичный' 'безналичный '
 'кредит' 'лизинг' 'нал' 'наличные' 'наличный' 'обмен+кредит' 'обмен+нал'
 'перечислением' nan]


<br>

Глянем распределение форм платежей.

In [133]:
df['payment_form'].value_counts(dropna=False)

NaN                                         25928
кредит                                       6190
безналичный                                  4276
Безналичная                                  1335
Собственные средства                          698
наличный                                      599
Наличная                                      499
Безналичная                                   204
Акция Собственные средства (Trade in 5%)       78
нал                                            58
trade-in                                       35
Перечисление                                   21
б/н                                             8
Без оплаты                                      8
Отсрочка платежа                                6
наличные                                        6
перечислением                                   6
Без.Наличный                                    5
лизинг                                          2
безналичный                                     2


Просто выделим $2$ категории:
* В кредит
* Своими деньгами

<br>

Не впервые решая эту задачу, создадим списки.

In [134]:
# в кредит
credit = ['кредит', 'Отсрочка платежа', 'лизинг', 'обмен+кредит', 'trade-in']

# наличный расчёт
cash = ['Без.Наличный', 'Безналичная', 'Безналичная ', 'Перечисление', 'б/н', 'безналичный', 'безналичный ', 'перечислением',\
        'обмен+нал', 'нал', 'наличные', 'наличный', 'Наличная', 'Акция Собственные средства (Trade in 5%)', 'Собственные средства']

# без оплаты
other = ['Без оплаты']

Заменим значения, устранив при этом дубликаты.

In [135]:
# словарь с заменами
payment_mapping = {
    **{value: 'В кредит' for value in credit},
    **{value: 'Наличный расчёт' for value in cash},
    **{value: np.NaN for value in other}
}

# переиначивание
df['payment_form'] = df['payment_form'].replace(payment_mapping)

<br>

Проверим.

In [136]:
duplicates('payment_form')

NaN                25936
Наличный расчёт     7796
В кредит            6234
Name: payment_form, dtype: int64

Количество непропущенных значений: 14030
Количество уникальных значений: 2

Первые 50 уникальных значений в алфавитном порядке:
['В кредит' 'Наличный расчёт' nan]


Разобрались.

<br>

`Количество авто в заказе`

In [137]:
duplicates('quantity')

1     37203
2      1017
3       452
4       282
5       185
6       120
7       100
8        79
10       63
9        61
Name: quantity, dtype: Int64

Количество непропущенных значений: 39960
Количество уникальных значений: 56

Первые 50 уникальных значений в алфавитном порядке:
<IntegerArray>
[-1,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
 38, 40, 41, 42, 43, 46, 47, 50, 51, 54, 60, 62]
Length: 50, dtype: Int64


Среди всех значений выбивается только одно: `-1`. Его нужно заменить просто на `1`.\
Пусть не смутит большое количество купленых автомобилей за раз.\
Потому что если "в заказе" больше двух автомобилей, то это явно юридическое лицо, и оно покупает авто с коммерческими целями.

In [138]:
# замена -1 на 1
df['quantity'] = df['quantity'].replace(-1, 1)

Поехали дальше.

<br>

`Цена авто в $`

In [139]:
duplicates('price_usd')

9885     559
11600    531
13800    428
12820    412
9894     402
7100     389
9969     315
11300    230
32753    222
9000     219
Name: price_usd, dtype: Int64

Количество непропущенных значений: 39966
Количество уникальных значений: 3382

Первые 50 уникальных значений в алфавитном порядке:
<IntegerArray>
[ 7100,  7300,  7363,  7426,  7460,  7500,  7509,  7542,  7560,  7904,  8027,
  8348,  8405,  8498,  8500,  8684,  8700,  8781,  8803,  8809,  8962,  9000,
  9048,  9112,  9117,  9159,  9260,  9307,  9455,  9500,  9519,  9600,  9612,
  9700,  9773,  9885,  9894,  9911,  9928,  9969, 10015, 10068, 10071, 10080,
 10115, 10117, 10119, 10121, 10122, 10223]
Length: 50, dtype: Int64


Здесь нечего смотреть.

<br>

`Цена заказа в $`

In [140]:
duplicates('sale_usd')

9885     559
12820    412
9894     402
9969     315
13800    230
32753    222
41664    214
33342    210
10015    208
31291    181
Name: sale_usd, dtype: Int64

Количество непропущенных значений: 39966
Количество уникальных значений: 4054

Первые 50 уникальных значений в алфавитном порядке:
<IntegerArray>
[-35588,      0,   7100,   7300,   7363,   7426,   7460,   7500,   7509,
   7542,   7560,   7904,   8027,   8348,   8405,   8498,   8500,   8684,
   8700,   8781,   8803,   8809,   8962,   9000,   9048,   9112,   9117,
   9159,   9260,   9307,   9455,   9500,   9519,   9600,   9612,   9700,
   9773,   9885,   9894,   9911,   9928,   9969,  10015,  10068,  10071,
  10080,  10115,  10117,  10119,  10121]
Length: 50, dtype: Int64


<br>

Из этого списка выбиваются следующие значения.

In [141]:
df[(df['sale_usd'] == 0) | (df['sale_usd'] == -35588)]

id  year   month     company                 car_type  brand  \
31874  31874  2019  Август  БИПЭК АВТО             Внедорожники    Kia   
31900  31900  2019  Август  БИПЭК АВТО      Легковые автомобили   Lada   
32068  32068  2019  Август  БИПЭК АВТО      Легковые автомобили   Lada   
33150  33150  2019  Август  БИПЭК АВТО             Внедорожники  Skoda   
33177  33177  2019  Август  БИПЭК АВТО      Легковые автомобили  Skoda   
34568  34568  2019  Август  БИПЭК АВТО  Коммерческие автомобили    UAZ   
34593  34593  2019  Август  БИПЭК АВТО             Внедорожники    UAZ   

          model    car_classification  manufacturing_year  \
31874  Sportage        Компактные SUV                2019   
31900    Granta               B класс                2019   
32068      XRAY               B класс                2018   
33150    Kodiaq    Полноразмерные SUV                2019   
33177    Superb               D класс                2019   
34568      3909  Развозные автомобили                2018   
34593   Patriot   Среднеразмерные SUV                2018   

                assembly_type manufacturing_country fuel_type  \
31874  Локальное производство  Республика Казахстан    Бензин   
31900  Локальное производство  Республика Казахстан    Бензин   
32068  Локальное производство  Республика Казахстан    Бензин   
33150  Локальное производство  Республика Казахстан    Бензин   
33177  Локальное производство  Республика Казахстан    Бензин   
34568  Локальное производство  Республика Казахстан    Бензин   
34593  Локальное производство  Республика Казахстан    Бензин   

       engine_displacement_l transmission_type      drive_type  \
31874                    2.0    Автоматическая    Полный (4WD)   
31900                    1.6             Робот  Передний (FWD)   
32068                    1.6      Механическая  Передний (FWD)   
33150                    2.0             Робот    Полный (4WD)   
33177                    2.0             Робот    Полный (4WD)   
34568                    2.7      Механическая    Полный (4WD)   
34593                    2.7      Механическая    Полный (4WD)   

                               region        city    dealer_center_name  \
31874          Карагандинская область   Караганда  БИПЭК АВТО Караганда   
31900                        г.Алматы      Алматы     БИПЭК АВТО Алматы   
32068            Павлодарская область   Экибастуз  БИПЭК АВТО Экибастуз   
33150                    г.Нур-Султан  Нур-Султан     БИПЭК АВТО Астана   
33177              Жамбылская область       Тараз      БИПЭК АВТО Тараз   
34568                        г.Алматы      Алматы     БИПЭК АВТО Алматы   
34593  Восточно-Казахстанская область       Семей      БИПЭК АВТО Семей   

      customer_type payment_form  quantity  price_usd  sale_usd  
31874           NaN          NaN      <NA>      20700         0  
31900           NaN          NaN      <NA>       7100         0  
32068           NaN          NaN      <NA>      13800         0  
33150           NaN          NaN      <NA>      40000         0  
33177           NaN          NaN         1      35588    -35588  
34568           NaN          NaN      <NA>      11200         0  
34593           NaN          NaN      <NA>      13800         0

Думаю, стоит просто присвоить им значения из колонки `price_usd`.

In [142]:
df.loc[(df['sale_usd'] == 0) | (df['sale_usd'] == -35588), 'sale_usd'] = df[(df['sale_usd'] == 0) | (df['sale_usd'] == -35588)]['price_usd']

С этой колонкой закончили.

<br>

**С неявными дубликатами и аномальными значениями разобрались.**

<br>

### Пропущенные данные

Разберёмся подробнее с пропусками.

Выведем количество пропусков и их процент.

In [143]:
# количество пропусков
df.isna().sum()

id                           0
year                         0
month                        0
company                      0
car_type                     0
brand                        0
model                        0
car_classification           0
manufacturing_year         501
assembly_type                0
manufacturing_country        0
fuel_type                 3140
engine_displacement_l     4275
transmission_type         3305
drive_type                4411
region                       0
city                         0
dealer_center_name           0
customer_type             7047
payment_form             25936
quantity                     6
price_usd                    0
sale_usd                     0
dtype: int64

In [144]:
# процент пропусков
round(df.isna().mean() * 100, 1)

id                        0.0
year                      0.0
month                     0.0
company                   0.0
car_type                  0.0
brand                     0.0
model                     0.0
car_classification        0.0
manufacturing_year        1.3
assembly_type             0.0
manufacturing_country     0.0
fuel_type                 7.9
engine_displacement_l    10.7
transmission_type         8.3
drive_type               11.0
region                    0.0
city                      0.0
dealer_center_name        0.0
customer_type            17.6
payment_form             64.9
quantity                  0.0
price_usd                 0.0
sale_usd                  0.0
dtype: float64

Много пропусков в колонке `payment_form`, $64.9$%, когда-то раньше мы это отмечали.

Вот список колонок, где есть пропуски.

In [145]:
df.columns[df.isna().any()]

Index(['manufacturing_year', 'fuel_type', 'engine_displacement_l',
       'transmission_type', 'drive_type', 'customer_type', 'payment_form',
       'quantity'],
      dtype='object')

<br>

**Сделаем функцию, которая будет помогать анализировать пропуски.**

In [146]:
def null_analysis(df, column):
    # копия главного датафрейма
    nan_df = df.copy()
    
    # приведение к строковому типу данных
    nan_df[column] = nan_df[column].astype('str')

    # сводная таблица
    nan_df = nan_df.pivot_table(index=['brand', 'model'], columns=column, aggfunc='size', fill_value=0).reset_index()

    # переименование колонки
    try:
        nan_df = nan_df.rename(columns={'nan': 'null_cnt'})
    except:
        pass
    
    try:
        nan_df = nan_df.rename(columns={'<NA>': 'null_cnt'})
    except:
        pass
    
    # выбор строк, где есть пропуски; сортировка по колонкам
    nan_df = nan_df[nan_df['null_cnt'] != 0].sort_values(by=['brand', 'null_cnt'], ascending=[True, False])
    
    # переместить 'null_cnt' в конец сводной таблицы
    nan_df = nan_df[[col for col in nan_df.columns if col != 'null_cnt'] + ['null_cnt']]

    # переименование индекса
    nan_df = nan_df.rename_axis(columns='index')

    # преобразование числовых колонок в числовой тип
    nan_df.iloc[:, 2:] = nan_df.iloc[:, 2:].astype('Int64')

    # количество наблюдений по модели
    nan_df['obs_cnt'] = nan_df.iloc[:, 2:].sum(axis=1).astype('Int64')

    # процент пропусков по модели
    nan_df['null_perc'] = nan_df['null_cnt'] / nan_df['obs_cnt'] * 100

    # преобразование колонки с процентом
    nan_df['null_perc'] = round(nan_df['null_perc'].astype(float), 1)

    # какой процент занимает модальное значение от всех непропущенных значений
    nan_df['mode_perc'] = nan_df.apply(lambda row: round(row.iloc[2:-3].max() / (row['obs_cnt'] - row['null_cnt']) * 100, 1) if (row['obs_cnt'] - row['null_cnt']) != 0 and row.iloc[2:-3].max() != 0 else 0, axis=1)

    # сверка пропусков и наблюдений сводной таблицы с данными датафрейма
    result_str = ''
    if nan_df['null_cnt'].sum() == df[column].isna().sum():
        result_str += f'Количество пропущенных значений в сводной таблице и основном датафрейме сходится.\n'
        result_str += f'В сводной: {nan_df["null_cnt"].sum()} пропусков. В датафрейме: {df[column].isna().sum()} пропусков.\n\n'
    else:
        result_str += 'Количество пропущенных значений в сводной таблице и основном датафрейме не сходится.\n'
        result_str += f'В сводной: {nan_df["null_cnt"].sum()} пропусков. В датафрейме: {df[column].isna().sum()} пропусков.\n\n'

    if nan_df['obs_cnt'].sum() == len(df[df['model'].isin(df[df[column].isna()]['model'].unique())]):
        result_str += 'Количество наблюдений в сводной таблице и основном датафрейме сходится.\n'
        result_str += f'В сводной: {nan_df["obs_cnt"].sum()} наблюдений. В датафрейме: {len(df[df["model"].isin(df[df[column].isna()]["model"].unique())])} наблюдений.\n\n'
    else: 
        result_str += 'Количество наблюдений в сводной таблице и основном датафрейме не сходится.\n'
        result_str += f'В сводной: {nan_df["obs_cnt"].sum()} наблюдений. В датафрейме: {len(df[df["model"].isin(df[df[column].isna()]["model"].unique())])} наблюдений.\n\n'
    
    return nan_df, result_str

<br>

#### Пропуски в `manufacturing_year`

In [147]:
df[df['manufacturing_year'].isna()].head()

id  year    month        company             car_type  brand model  \
5048  5048  2019  Февраль  Автомир-Центр  Легковые автомобили  Mazda     3   
5049  5049  2019  Февраль  Автомир-Центр  Легковые автомобили  Mazda     3   
5050  5050  2019  Февраль  Автомир-Центр  Легковые автомобили  Mazda     6   
5051  5051  2019  Февраль  Автомир-Центр         Внедорожники  Mazda  CX-5   
5052  5052  2019  Февраль  Автомир-Центр         Внедорожники  Mazda  CX-5   

     car_classification  manufacturing_year assembly_type  \
5048            C класс                <NA>        Импорт   
5049            C класс                <NA>        Импорт   
5050            D класс                <NA>        Импорт   
5051     Компактные SUV                <NA>        Импорт   
5052     Компактные SUV                <NA>        Импорт   

     manufacturing_country fuel_type  engine_displacement_l transmission_type  \
5048  Российская Федерация       NaN                    NaN               NaN   
5049  Российская Федерация       NaN                    NaN               NaN   
5050  Российская Федерация       NaN                    NaN               NaN   
5051  Российская Федерация       NaN                    NaN               NaN   
5052  Российская Федерация       NaN                    NaN               NaN   

     drive_type                  region        city       dealer_center_name  \
5048        NaN  Карагандинская область   Караганда  Автомир-Центр Караганда   
5049        NaN            г.Нур-Султан  Нур-Султан     Автомир-Центр Астана   
5050        NaN            г.Нур-Султан  Нур-Султан     Автомир-Центр Астана   
5051        NaN  Карагандинская область   Караганда  Автомир-Центр Караганда   
5052        NaN  Карагандинская область   Караганда  Автомир-Центр Караганда   

     customer_type     payment_form  quantity  price_usd  sale_usd  
5048           NaN  Наличный расчёт         1      21547     21547  
5049           NaN  Наличный расчёт         1      21547     21547  
5050           NaN         В кредит         1      24998     24998  
5051           NaN         В кредит         3      26684     80053  
5052           NaN  Наличный расчёт         3      26684     80053

In [148]:
df['manufacturing_year'].value_counts(dropna=False).head(10)

2019    30026
2018     9081
NaN       501
2017      324
2016       30
2014        2
2011        1
2013        1
Name: manufacturing_year, dtype: Int64

Здесь пропуски — третье самое встречаемое значение.

<br>

Применим функцию.

In [149]:
# Пример использования функции
pt_man, str_man = null_analysis(df, 'manufacturing_year')

In [150]:
# вывод строк с пропусками и наблюдениями
print(str_man)

# компактная таблица
pt_man.head()

# раскомментируйте код, чтобы увидеть всю сводную таблицу
# pt_man

Количество пропущенных значений в сводной таблице и основном датафрейме сходится.
В сводной: 501 пропусков. В датафрейме: 501 пропусков.

Количество наблюдений в сводной таблице и основном датафрейме сходится.
В сводной: 4978 наблюдений. В датафрейме: 4978 наблюдений.




index                brand    model  2011  2013  2014  2016  2017  2018  2019  \
16                     BMW  7 серия     0     0     0     0     0     1     5   
65     Hyundai Truck & Bus     H350     0     0     0     0     5     0     3   
70     Hyundai Truck & Bus    HD 78     0     0     0     0     1     0    11   
68     Hyundai Truck & Bus    HD 35     0     0     0     0     4     0    11   
69     Hyundai Truck & Bus    HD 65     0     0     0     0     4     5     7   

index  null_cnt  obs_cnt  null_perc  mode_perc  
16            1        7       14.3       83.3  
65           32       40       80.0       62.5  
70           30       42       71.4       91.7  
68           15       30       50.0       73.3  
69            8       24       33.3       43.8

**Итак, какую сводную таблицу создала функция:**
1. В качестве индексов выступают марка и модель автомобиля.
2. В качестве колонок выступают года, когда был произведён автомобиль.
3. С помощью агрегирующей функции мы подсчитываем количество автомобилей, произведённых в определённый год.
4. `null_cnt` значит количество пропусков у конкретной модели за все годы.
5. `obs_cnt` значит количество наблюдений **(это включая пропуски)** у конкретной модели.
6. `null_perc` какой процент от **всех наблюдений** занимают пропуски.
7. `mode_perc` значит, какой процент составляет модальное (самое частотное) значение из всех **непропущенных значений**.

Сводные таблицы по умолчанию **отсортированы по марке авто в лексикографическом порядке и по убыванию количества пропущенных значений.**

<br>

Заполнять пропуски будем модой.\
Я уверен, что это неточный способ, ведь чем ниже процент, который занимает модальное значение, тем выше вероятность неточности.\
Лучший способ мне пока неизвестен.\
**Применим правило: если модальное значение занимает процент, равный или больше $60$, то это модальное значение заменит пропуск в годе производства для этой модели.**

In [151]:
# итерация по строкам таблицы pt_man с использованием метода iterrows(): index — строка, row — колонка
for index, row in pt_man.iterrows():
    # извлечение значения 'model' для текущей строки
    model = row['model']
    # извлечение значения 'mode_perc' для текущей строки
    mode_perc = row['mode_perc']
    
    # если процент модального значения >= 60 для данной модели
    if mode_perc >= 60:
        # то находим модальное значение года производства для неё
        mode_value = df[df['model'] == model]['manufacturing_year'].mode()
        
        # если mode_value не является пропуском
        if pd.notna(mode_value.iloc[0]):
            # то заполняем пропуски в годе производства модальным значением для данной модели
            df.loc[(df['model'] == model) & (df['manufacturing_year'].isna()), 'manufacturing_year'] = mode_value.iloc[0]

<br>

Проверим результат.

In [152]:
# запишем в иные переменные
pt_man_fill, str_man_fill = null_analysis(df, 'manufacturing_year')

print(str_man_fill)
pt_man_fill

Количество пропущенных значений в сводной таблице и основном датафрейме сходится.
В сводной: 27 пропусков. В датафрейме: 27 пропусков.

Количество наблюдений в сводной таблице и основном датафрейме сходится.
В сводной: 203 наблюдений. В датафрейме: 203 наблюдений.




index                brand         model  2011  2013  2014  2016  2017  2018  \
69     Hyundai Truck & Bus         HD 65     0     0     0     0     4     5   
66     Hyundai Truck & Bus        HD 160     0     0     0     0     0     0   
146             Land Rover   Range Rover     0     0     0     0     2    41   
165                  Mazda             3     0     0     0     0     0     0   
196             Mitsubishi  Pajero Sport     0     0     0     0     0    27   
267                  Volvo          XC60     0     0     0     0     0     8   

index  2019  null_cnt  obs_cnt  null_perc  mode_perc  
69        7         8       24       33.3       43.8  
66        0         1        1      100.0        0.0  
146      41         1       85        1.2       48.8  
165       0         5        5      100.0        0.0  
196      32        11       70       15.7       54.2  
267       9         1       18        5.6       52.9

Итак, остались пропуски по этим моделям. 

<br>

#### Пропуски в `fuel_type`

In [153]:
df[df['fuel_type'].isna()].head()

id  year   month     company                 car_type      brand  \
97      97  2019  Январь       СемАЗ  Коммерческие автомобили  Dong Feng   
99      99  2019  Январь       СемАЗ  Коммерческие автомобили      Foton   
1056  1056  2019  Январь  Allur Auto  Коммерческие автомобили      Iveco   
1068  1068  2019  Январь  Allur Auto             Внедорожники        Jac   
1069  1069  2019  Январь  Allur Auto             Внедорожники        Jac   

               model       car_classification  manufacturing_year  \
97        BWC6665GA5         Средние автобусы                2019   
99    BJ1069VDJEA-F1  Малотоннажные грузовики                2018   
1056           Daily  Малотоннажные грузовики                2017   
1068              S3        Субкомпактные SUV                2018   
1069              S3        Субкомпактные SUV                2018   

               assembly_type manufacturing_country fuel_type  \
97    Локальное производство  Республика Казахстан       NaN   
99    Локальное производство  Республика Казахстан       NaN   
1056  Локальное производство  Республика Казахстан       NaN   
1068  Локальное производство  Республика Казахстан       NaN   
1069  Локальное производство  Республика Казахстан       NaN   

      engine_displacement_l transmission_type          drive_type  \
97                      NaN               NaN                 NaN   
99                      NaN               NaN                 NaN   
1056                    NaN               NaN                 NaN   
1068                    NaN               NaN  Двухколёсный (2WD)   
1069                    NaN               NaN  Двухколёсный (2WD)   

               region        city    dealer_center_name     customer_type  \
97       г.Нур-Султан  Нур-Султан                 СемАЗ               NaN   
99           г.Алматы      Алматы  Меридиан АВТО Алматы               NaN   
1056         г.Алматы      Алматы     Allur Auto Almaty  Юридическое лицо   
1068  Экспорт область     ЭКСПОРТ     Allur Auto Almaty  Юридическое лицо   
1069  Экспорт область     ЭКСПОРТ     Allur Auto Almaty  Юридическое лицо   

     payment_form  quantity  price_usd  sale_usd  
97            NaN        29      26693    774091  
99            NaN         3      13619     40858  
1056          NaN         1      27750     27750  
1068          NaN         1      12818     12818  
1069          NaN         1      12818     12818

In [154]:
df['fuel_type'].value_counts(dropna=False).head(10)

Бензин           35000
NaN               3140
Дизель            1803
Электричество       13
Гибрид              10
Name: fuel_type, dtype: int64

Здесь пропуски — второе самое встречаемое значение.

<br>

Применим функцию.

In [155]:
pt_fuel, str_fuel = null_analysis(df, 'fuel_type')

In [156]:
# вывод строк с пропусками и наблюдениями
print(str_fuel)

# раскомментируйте код, чтобы увидеть всю сводную таблицу
# pd.set_option('display.max_rows', None)
pt_fuel

# раскомментируйте код, чтобы снова сделать таблицу компактной
# pd.reset_option('display.max_rows')
pt_fuel

Количество пропущенных значений в сводной таблице и основном датафрейме сходится.
В сводной: 3140 пропусков. В датафрейме: 3140 пропусков.

Количество наблюдений в сводной таблице и основном датафрейме сходится.
В сводной: 7373 наблюдений. В датафрейме: 7373 наблюдений.




index      brand           model  Бензин  Гибрид  Дизель  Электричество  \
3          ANKAI        HFF6850G       0       0     167              0   
0          ANKAI         HF-D105       0       0       0              0   
40     Dong Feng      BWC6665GA5       0       0       0              0   
43         Foton  BJ1069VDJEA-F1       0       0       0              0   
44         Foton  BJ3253DMPKB-AD       0       0       0              0   
..           ...             ...     ...     ...     ...            ...   
271         Урал            4320       0       0       0              0   
274         Урал            5557       0       0       0              0   
270         Урал           32551       0       0       0              0   
272         Урал    4320-1951-40       0       0       0              0   
273         Урал    4320-1951-60       0       0       0              0   

index  null_cnt  obs_cnt  null_perc  mode_perc  
3            73      240       30.4      100.0  
0            30       30      100.0        0.0  
40           10       10      100.0        0.0  
43           19       19      100.0        0.0  
44            9        9      100.0        0.0  
..          ...      ...        ...        ...  
271           7        7      100.0        0.0  
274           2        2      100.0        0.0  
270           1        1      100.0        0.0  
272           1        1      100.0        0.0  
273           1        1      100.0        0.0  

[73 rows x 10 columns]

Проанализировав эту сводную таблицу, можно заполнить пропуски в типе топлива модальным значением.\
Только автомобили марки `Mazda` и `Renault` придётся заполнить вручную, там пропусков много. И ещё по некоторым грузовикам и автобусам то же самое нужно проделать.

**Применим правило: если модальное значение занимает процент, равный или больше  $60$, то это модальное значение заменит пропуск в виде топлива для этой модели.**

In [157]:
# итерация по строкам таблицы pt_fuel с использованием метода iterrows(): index — строка, row — колонка
for index, row in pt_fuel.iterrows():
    # извлечение значения 'model' для текущей строки
    model = row['model']
    # извлечение значения 'mode_perc' для текущей строки
    mode_perc = row['mode_perc']
    
    # если процент модального значения >= 60 для данной модели
    if mode_perc >= 60:
        # то находим модальное значение вида топлива для неё
        mode_value = df[df['model'] == model]['fuel_type'].mode()
        
        # если mode_value не является пропуском
        if pd.notna(mode_value.iloc[0]):
            # то заполняем пропуски в виде топлива модальным значением для данной модели
            df.loc[(df['model'] == model) & df['fuel_type'].isna(), 'fuel_type'] = mode_value.iloc[0]

<br>

Ручная замена.

In [158]:
diesel = ['Master', 'Dokker', 'SX3258DR384', 'HF-D105', 'BJ1069VDJEA-F1']
petrol = ['Logan', 'Kaptur', 'Arkana', 'Koleos', '6', '3', 'CX-5', 'CX-9']

In [159]:
for model in diesel:
    df.loc[(df['model'] == model) & (df['fuel_type'].isna()), 'fuel_type'] = 'Дизель'
    
for model in petrol:
    df.loc[(df['model'] == model) & (df['fuel_type'].isna()), 'fuel_type'] = 'Бензин'

<br>

Проверим результат.

In [160]:
# запишем в иные переменные
pt_fuel_fill, str_fuel_fill = null_analysis(df, 'fuel_type')

print(str_fuel_fill)
pt_fuel_fill.sort_values(by='null_cnt', ascending=False)

Количество пропущенных значений в сводной таблице и основном датафрейме сходится.
В сводной: 47 пропусков. В датафрейме: 47 пропусков.

Количество наблюдений в сводной таблице и основном датафрейме сходится.
В сводной: 47 наблюдений. В датафрейме: 47 наблюдений.




index                brand           model  Бензин  Гибрид  Дизель  \
40               Dong Feng      BWC6665GA5       0       0       0   
44                   Foton  BJ3253DMPKB-AD       0       0       0   
271                   Урал            4320       0       0       0   
64     Hyundai Truck & Bus             EX8       0       0       0   
87                   Iveco          Tipper       0       0       0   
84                   Iveco         Daily A       0       0       0   
86                   Iveco         Stralis       0       0       0   
274                   Урал            5557       0       0       0   
66     Hyundai Truck & Bus          HD 160       0       0       0   
85                   Iveco         Daily V       0       0       0   
270                   Урал           32551       0       0       0   
272                   Урал    4320-1951-40       0       0       0   
273                   Урал    4320-1951-60       0       0       0   

index  Электричество  null_cnt  obs_cnt  null_perc  mode_perc  
40                 0        10       10      100.0          0  
44                 0         9        9      100.0          0  
271                0         7        7      100.0          0  
64                 0         6        6      100.0          0  
87                 0         4        4      100.0          0  
84                 0         2        2      100.0          0  
86                 0         2        2      100.0          0  
274                0         2        2      100.0          0  
66                 0         1        1      100.0          0  
85                 0         1        1      100.0          0  
270                0         1        1      100.0          0  
272                0         1        1      100.0          0  
273                0         1        1      100.0          0

Что за транспортные средства остались?

In [161]:
df.loc[df['model'].isin(pt_fuel_fill['model'].unique())]['car_classification'].unique()

array(['Средние автобусы', 'Малотоннажные грузовики',
       'Крупнотоннажные грузовики', 'Микроавтобусы',
       'Развозные автомобили', 'Среднетоннажные грузовики'], dtype=object)

Как видим, это грузовики и автобусы. Отнесём их к дизелю.

In [162]:
df.loc[df['model'].isin(pt_fuel_fill['model'].unique()), 'fuel_type'] = 'Дизель'

Проверим пропуски.

In [163]:
df['fuel_type'].isna().sum()

0

Пропусков здесь больше нет.

<br>

<br>

#### Пропуски в `engine_displacement_l`

In [164]:
df[df['engine_displacement_l'].isna()].head()

id  year   month    company                 car_type      brand  \
97      97  2019  Январь      СемАЗ  Коммерческие автомобили  Dong Feng   
99      99  2019  Январь      СемАЗ  Коммерческие автомобили      Foton   
1052  1052  2019  Январь  СВС-ТРАНС  Коммерческие автомобили      Isuzu   
1053  1053  2019  Январь  СВС-ТРАНС  Коммерческие автомобили      Isuzu   
1054  1054  2019  Январь  СВС-ТРАНС  Коммерческие автомобили      Isuzu   

               model         car_classification  manufacturing_year  \
97        BWC6665GA5           Средние автобусы                2019   
99    BJ1069VDJEA-F1    Малотоннажные грузовики                2018   
1052           NMS85  Среднетоннажные грузовики                2018   
1053             NPR    Малотоннажные грузовики                2018   
1054             NPR    Малотоннажные грузовики                2018   

               assembly_type manufacturing_country fuel_type  \
97    Локальное производство  Республика Казахстан    Дизель   
99    Локальное производство  Республика Казахстан    Дизель   
1052                  Импорт  Российская Федерация    Дизель   
1053                  Импорт  Российская Федерация    Дизель   
1054                  Импорт  Российская Федерация    Дизель   

      engine_displacement_l transmission_type          drive_type  \
97                      NaN               NaN                 NaN   
99                      NaN               NaN                 NaN   
1052                    NaN               NaN        Полный (4WD)   
1053                    NaN               NaN  Двухколёсный (2WD)   
1054                    NaN               NaN  Двухколёсный (2WD)   

            region        city    dealer_center_name customer_type  \
97    г.Нур-Султан  Нур-Султан                 СемАЗ           NaN   
99        г.Алматы      Алматы  Меридиан АВТО Алматы           NaN   
1052      г.Алматы      Алматы            CBC Алматы           NaN   
1053      г.Алматы      Алматы            CBC Алматы           NaN   
1054      г.Алматы      Алматы            CBC Алматы           NaN   

     payment_form  quantity  price_usd  sale_usd  
97            NaN        29      26693    774091  
99            NaN         3      13619     40858  
1052          NaN         1      44146     44146  
1053          NaN         1      37000     37000  
1054          NaN         1      37000     37000

In [165]:
df['engine_displacement_l'].value_counts(dropna=False).head(10)

1.6    9075
2.0    8133
2.7    5074
2.5    5034
NaN    4275
1.5    1559
2.4    1247
1.7     833
3.5     788
4.6     754
Name: engine_displacement_l, dtype: int64

Здесь пропуски — пятое самое встречаемое значение.

<br>

Применим функцию.

In [166]:
pt_engine, str_engine = null_analysis(df, 'engine_displacement_l')

In [167]:
# вывод строк с пропусками и наблюдениями
print(str_engine)

# раскомментируйте код, чтобы увидеть всю сводную таблицу
pd.set_option('display.max_rows', None)
pt_engine

# раскомментируйте код, чтобы снова сделать таблицу компактной
pd.reset_option('display.max_rows')
pt_engine.sort_values(by='null_perc', ascending=False)

Количество пропущенных значений в сводной таблице и основном датафрейме сходится.
В сводной: 4275 пропусков. В датафрейме: 4275 пропусков.

Количество наблюдений в сводной таблице и основном датафрейме сходится.
В сводной: 11975 наблюдений. В датафрейме: 11975 наблюдений.




index       brand        model  1.2  1.3  1.4  1.5  1.6  1.7  1.8  10.5  11.0  \
118         KAMAZ       58815Z    0    0    0    0    0    0    0     0     0   
116         KAMAZ        54115    0    0    0    0    0    0    0     0     0   
125         KAMAZ        65225    0    0    0    0    0    0    0     0     0   
110         KAMAZ        45141    0    0    0    0    0    0    0     0     0   
124         KAMAZ        65206    0    0    0    0    0    0    0     0     0   
..            ...          ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   
257    Volkswagen         Polo    0    0    0    0  512    0    0     0     0   
51            GAZ         3308    0    0    0    0    0    0    0     0     0   
146    Land Rover  Range Rover    0    0    0    0    0    0    0     0     0   
237        Toyota     HILUX DC    0    0    0    0    0    0    0     0     0   
235        Toyota      Corolla    0    7    0    0  190    0    0     0     0   

index  12.0  12.3  12.8  13.0  2.0  2.2  2.4  2.5  2.7  2.8  2.9  3.0  3.3  \
118       0     0     0     0    0    0    0    0    0    0    0    0    0   
116       0     0     0     0    0    0    0    0    0    0    0    0    0   
125       0     0     0     0    0    0    0    0    0    0    0    0    0   
110       0     0     0     0    0    0    0    0    0    0    0    0    0   
124       0     0     0     0    0    0    0    0    0    0    0    0    0   
..      ...   ...   ...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
257       0     0     0     0    3    0    0    0    0    0    0    0    0   
51        0     0     0     0    0    0    0    0    1    0    0    0    0   
146       0     0     0     0   16    0    0    0    0    0    0   29    0   
237       0     0     0     0    0    0  298    0  502   25    0    0    0   
235       0     0     0     0    0    0    0    0  759    0    0    0    0   

index  3.5  3.6  3.8  3.9  4.0  4.3  4.4  4.6  4.9  5.0  5.2  5.5  5.6  5.7  \
118      0    0    0    0    0    0    0    0    0    0    0    0    0    0   
116      0    0    0    0    0    0    0    0    0    0    0    0    0    0   
125      0    0    0    0    0    0    0    0    0    0    0    0    0    0   
110      0    0    0    0    0    0    0    0    0    0    0    0    0    0   
124      0    0    0    0    0    0    0    0    0    0    0    0    0    0   
..     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
257      0    0    0    0    0    0    0    0    0    0    0    0    0    0   
51       0    0    0    0    0   53    0    0    0    0    0    0    0    0   
146      0    0    0    0    0    0    0    0    0   39    0    0    0    0   
237      0    0    0    0    0    0    0    0    0    0    0    0    0    0   
235      0    0    0    0  131    0    0    0    0    0    0    0    0    0   

index  6.2  6.5  6.6  6.7  7.5  7.6  8.4  8.7  null_cnt  obs_cnt  null_perc  \
118      0    0    0    0    0    0    0    0        15       15      100.0   
116      0    0    0    0    0    0    0    0        17       17      100.0   
125      0    0    0    0    0    0    0    0         3        3      100.0   
110      0    0    0    0    0    0    0    0         3        3      100.0   
124      0    0    0    0    0    0    0    0         4        4      100.0   
..     ...  ...  ...  ...  ...  ...  ...  ...       ...      ...        ...   
257      0    0    0    0    0    0    0    1        28      544        5.1   
51       0    0    0    0    0    0    0    0         1       55        1.8   
146      0    0    0    0    0    0    0    0         1       85        1.2   
237      0    0    0    0    0    0    0    0         2      827        0.2   
235      0    0    0    0    0    0    0    0         2     1089        0.2   

index  mode_perc  
118          0.0  
116          0.0  
125          0.0  
110          0.0  
124          0.0  
..           ...  
257         99.2  
51          98.1  
146         46.4  
23

Здесь ситуация сложнее.

<br>

**Применим правило: если модальное значение занимает процент, равный или больше  $60$, и процент пропусков не превышает $50$, то это модальное значение заменит пропуск в виде топлива для этой модели.**

In [168]:
# итерация по строкам таблицы pt_fuel с использованием метода iterrows(): index — строка, row — колонка
for index, row in pt_engine.iterrows():
    # извлечение значения 'model' для текущей строки
    model = row['model']
    # извлечение значения 'mode_perc' для текущей строки
    mode_perc = row['mode_perc']
    # извлечение значения 'null_perc' для текущей строки
    null_perc = row['null_perc']
    
    # если процент модального значения >= 60 для данной модели и процент пропусков не больше 90
    if mode_perc >= 60 and null_perc <= 90:
        # то находим модальное значение вида топлива для неё
        mode_value = df[df['model'] == model]['engine_displacement_l'].mode()
        
        # если mode_value не является пустотой из-за того, что все значения у модели уникальны, and если mode_value не является пропуском
        if not mode_value.empty and pd.notna(mode_value.iloc[0]):
            # то заполняем пропуски в виде топлива модальным значением для данной модели
            df.loc[(df['model'] == model) & df['engine_displacement_l'].isna(), 'engine_displacement_l'] = mode_value.iloc[0]

<br>

По моделям, у которых вообще не указан объём двигателя, одни пропуски:\
`Logan` и `Sandero` есть только в одном виде — $1.6$ литра.\
Вообще, где буду указывать объём двигателя вручную, там я руководствовался информацией из одного автомобильного портала, где продаются машины.

По другим автомобилям `Renault` есть `2` мотора разных объёмов. Мы не можем здесь угадывать.\
По автомобилям `Mazda` та же картина. Тут не угадаешь.

<br>

Заполним двигатели транспорта, в котором я уверен.

In [169]:
df.loc[(df['model'] == 'Logan') | (df['model'] == 'Sandero'), 'engine_displacement_l'] = 1.6
df.loc[df['model'] == '65115', 'engine_displacement_l'] = 6.7

<br>

Проверим результат.

In [170]:
# запишем в иные переменные
pt_engine_fill, str_engine_fill = null_analysis(df, 'engine_displacement_l')

print(str_engine_fill)

pd.set_option('display.max_rows', None)
pt_engine_fill.sort_values(by='null_cnt', ascending=False)

pd.reset_option('display.max_rows', None)
pt_engine_fill.sort_values(by='null_cnt', ascending=False).head(20)

Количество пропущенных значений в сводной таблице и основном датафрейме сходится.
В сводной: 1945 пропусков. В датафрейме: 1945 пропусков.

Количество наблюдений в сводной таблице и основном датафрейме сходится.
В сводной: 2091 наблюдений. В датафрейме: 2091 наблюдений.




index                brand        model  1.2  1.3  1.4  1.5  1.6  1.7  1.8  \
214                Renault       Duster    0    0    0    0   15    0    0   
215                Renault       Kaptur    0    0    0    0    0    0    0   
106                  KAMAZ        43118    0    0    0    0    0    0    0   
123                  KAMAZ         6520    0    0    0    0    0    0    0   
112                  KAMAZ        45143    0    0    0    0    0    0    0   
212                Renault       Arkana    0    0    0    0    0    0    0   
121                  KAMAZ        65116    0    0    0    0    0    0    0   
167                  Mazda         CX-5    0    0    0    0    0    0    0   
109                  KAMAZ        44108    0    0    0    0    0    0    0   
224                Shacman  SX3258DR384    0    0    0    0    0    0    0   
70     Hyundai Truck & Bus        HD 78    0    0    0    0    0    0    0   
213                Renault       Dokker    0    0    0    0    0    0    0   
117                  KAMAZ         5490    0    0    0    0    0    0    0   
166                  Mazda            6    0    0    0    0    0    0    0   
0                    ANKAI      HF-D105    0    0    0    0    0    0    0   
122                  KAMAZ        65117    0    0    0    0    0    0    0   
107                  KAMAZ        43253    0    0    0    0    0    0    0   
113                  KAMAZ        53215    0    0    0    0    0    0    0   
168                  Mazda         CX-9    0    0    0    0    0    0    0   
111                  KAMAZ        45142    0    0    0    0    0    0    0   

index  10.5  11.0  12.0  12.3  12.8  13.0  2.0  2.2  2.4  2.5  2.7  2.8  2.9  \
214       0     0     0     0     0     0   42    0    0    0    0    0    0   
215       0     0     0     0     0     0    0    0    0    0    0    0    0   
106       0     0     0     0     0     0    0    0    0    0    0    0    0   
123       0     0     0     0     0     0    0    0    0    0    0    0    0   
112       0     0     0     0     0     0    0    0    0    0    0    0    0   
212       0     0     0     0     0     0    0    0    0    0    0    0    0   
121       0     0     0     0     0     0    0    0    0    0    0    0    0   
167       0     0     0     0     0     0    0    0    0    0    0    0    0   
109       0     0     0     0     0     0    0    0    0    0    0    0    0   
224       0     0     0     0     0     0    0    0    0    0    0    0    0   
70        0     0     0     0     0     0    0    0    0    0    0    0    0   
213       0     0     0     0     0     0    0    0    0    0    0    0    0   
117       0     0     0     0     0     0    0    0    0    0    0    0    0   
166       0     0     0     0     0     0    0    0    0    0    0    0    0   
0         0     0     0     0     0     0    0    0    0    0    0    0    0   
122       0     0     0     0     0     0    0    0    0    0    0    0    0   
107       0     0     0     0     0     0    0    0    0    0    0    0    0   
113       0     0     0     0     0     0    0    0    0    0    0    0    0   
168       0     0     0     0     0     0    0    0    0    0    0    0    0   
111       0     0     0     0     0     0    0    0    0    0    0    0    0   

index  3.0  3.3  3.5  3.6  3.8  3.9  4.0  4.3  4.4  4.6  4.9  5.0  5.2  5.5  \
214      0    0    0    0    0    0    0    0    0    0    0    0    0    0   
215      0    0    0    0    0    0    0    0    0    0    0    0    0    0   
106      0    0    0    0    0    0    0    0    0    0    0    0    0    0   
123      0    0    0    0    0    0    0    0    0    0    0    0    0    0   
112      0    0    0    0    0    0    0    0    0    0    0    0    0    0   
212      0    0    0    0    0    0    0    0    0    0    0    0    0    0   
121      0    0    0    0    0    0    0    0    0    0    0    0    0    0   
167      0    0    0    0    0    0    0    0   

<br>

<br>

<br>

<br>

<br>

<br>

<br>

<br>

<br>

# черновик начинается

Пропуски в `transmission_type`.

In [171]:
df[df['transmission_type'].isna()].head()

id  year   month    company                 car_type      brand  \
97      97  2019  Январь      СемАЗ  Коммерческие автомобили  Dong Feng   
99      99  2019  Январь      СемАЗ  Коммерческие автомобили      Foton   
1052  1052  2019  Январь  СВС-ТРАНС  Коммерческие автомобили      Isuzu   
1053  1053  2019  Январь  СВС-ТРАНС  Коммерческие автомобили      Isuzu   
1054  1054  2019  Январь  СВС-ТРАНС  Коммерческие автомобили      Isuzu   

               model         car_classification  manufacturing_year  \
97        BWC6665GA5           Средние автобусы                2019   
99    BJ1069VDJEA-F1    Малотоннажные грузовики                2018   
1052           NMS85  Среднетоннажные грузовики                2018   
1053             NPR    Малотоннажные грузовики                2018   
1054             NPR    Малотоннажные грузовики                2018   

               assembly_type manufacturing_country fuel_type  \
97    Локальное производство  Республика Казахстан    Дизель   
99    Локальное производство  Республика Казахстан    Дизель   
1052                  Импорт  Российская Федерация    Дизель   
1053                  Импорт  Российская Федерация    Дизель   
1054                  Импорт  Российская Федерация    Дизель   

      engine_displacement_l transmission_type          drive_type  \
97                      NaN               NaN                 NaN   
99                      NaN               NaN                 NaN   
1052                    NaN               NaN        Полный (4WD)   
1053                    5.2               NaN  Двухколёсный (2WD)   
1054                    5.2               NaN  Двухколёсный (2WD)   

            region        city    dealer_center_name customer_type  \
97    г.Нур-Султан  Нур-Султан                 СемАЗ           NaN   
99        г.Алматы      Алматы  Меридиан АВТО Алматы           NaN   
1052      г.Алматы      Алматы            CBC Алматы           NaN   
1053      г.Алматы      Алматы            CBC Алматы           NaN   
1054      г.Алматы      Алматы            CBC Алматы           NaN   

     payment_form  quantity  price_usd  sale_usd  
97            NaN        29      26693    774091  
99            NaN         3      13619     40858  
1052          NaN         1      44146     44146  
1053          NaN         1      37000     37000  
1054          NaN         1      37000     37000

In [172]:
df['transmission_type'].value_counts(dropna=False).head(10)

Автоматическая    23637
Механическая       8409
Вариатор           3857
NaN                3305
Робот               745
Редуктор             13
Name: transmission_type, dtype: int64

<br>

Применим функцию.

In [173]:
# раскомментируйте код, чтобы увидеть всю сводную таблицу
# pd.set_option('display.max_rows', None)

# display(null_analysis(df, 'transmission_type').head())

# раскомментируйте код, чтобы снова сделать таблицу компактной
# pd.reset_option('display.max_rows')

Здесь пропуски — четвёртое самое встречаемое значение. Но с ними ничего не поделаешь. Их нужно оставить как есть.\
Тут видно, что вместе с пропусками в этой колонке видны пропуски в других колонках.

<br>

Пропуски в `drive_type`.

In [174]:
# df[df['drive_type'].isna()].head()

In [175]:
# df['drive_type'].value_counts(dropna=False).head(10)

Здесь пропуски — пятое самое встречаемое значение. Но с ними ничего не поделаешь. Их нужно оставить как есть.\
Тут видно, что вместе с пропусками в этой колонке видны пропуски в других колонках.

<br>

Применим функцию.

In [176]:
# раскомментируйте код, чтобы увидеть всю сводную таблицу
# pd.set_option('display.max_rows', None)

# display(null_analysis(df, 'drive_type').head())

# раскомментируйте код, чтобы снова сделать таблицу компактной
# pd.reset_option('display.max_rows')

<br>

Пропуски в `customer_type`.

In [177]:
# df[df['customer_type'].isna()].head()

In [178]:
# df['customer_type'].value_counts(dropna=False).head(10)

Здесь пропуски — третье самое встречаемое значение.\
Можно предположить, что тип покупателя зависит от "размера заказа".\
Рядовой человек приходит в автосалон, чтобы купить себе один автомобиль.\
Но если в "заказе" у нас больше одного-двух автомобилей, то несложно догадаться, что они покупаются для коммерческих целей.\
Следовательно, это юридическое лицо.

<br>

Применим функцию.

In [179]:
# раскомментируйте код, чтобы увидеть всю сводную таблицу
# pd.set_option('display.max_rows', None)

# display(null_analysis(df, 'customer_type').head())

# раскомментируйте код, чтобы снова сделать таблицу компактной
# pd.reset_option('display.max_rows')

<br>

<br>

In [180]:
# раскомментируйте код, чтобы увидеть всю сводную таблицу
# pd.set_option('display.max_rows', None)

# display(null_analysis(df, 'quantity').head())

# раскомментируйте код, чтобы снова сделать таблицу компактной
# pd.reset_option('display.max_rows')

In [181]:
# раскомментируйте код, чтобы увидеть всю сводную таблицу
# pd.set_option('display.max_rows', None)

# display(null_analysis(df, 'payment_form').head())

# раскомментируйте код, чтобы снова сделать таблицу компактной
# pd.reset_option('display.max_rows')

In [182]:
# df

In [183]:
# df.pivot_table(index='customer_type', columns='quantity', aggfunc='size')

# ф-ция пропусков customer_type
def customer(column)
    # копия главного датафрейма
    nan_df = df.copy()
    
    # приведение к строковому типу данных
    nan_df['customer_type'] = nan_df['customer_type'].astype('str')

    # сводная таблица
    nan_df = nan_df.pivot_table(index='quantity', columns='customer_type', aggfunc='size', fill_value=0).reset_index()

    # переименование колонки
    try:
        nan_df = nan_df.rename(columns={'nan': 'null_cnt'})
    except:
        pass
    
    try:
        nan_df = nan_df.rename(columns={'<NA>': 'null_cnt'})
    except:
        pass
    
    # выбор строк, где есть пропуски; сортировка по колонкам
    nan_df = nan_df[nan_df['null_cnt'] != 0]
    
    # переместить 'null_cnt' в конец сводной таблицы
    nan_df = nan_df[[col for col in nan_df.columns if col != 'null_cnt'] + ['null_cnt']]

    # переименование индекса
    nan_df = nan_df.rename_axis(columns='index')

    # преобразование числовых колонок в числовой тип
    nan_df.iloc[:, 2:] = nan_df.iloc[:, 2:].astype('Int64')

    # количество наблюдений по модели
    nan_df['obs_cnt'] = nan_df.iloc[:, 2:].sum(axis=1).astype('Int64')

    # процент пропусков по модели
    nan_df['null_perc'] = nan_df['null_cnt'] / nan_df['obs_cnt'] * 100

    # преобразование колонки с процентом
    nan_df['null_perc'] = round(nan_df['null_perc'].astype(float), 1)

    # какой процент занимает модальное значение от всех непропущенных значений
    nan_df['mode_perc'] = nan_df.apply(lambda row: round(row.iloc[2:-3].max() / (row['obs_cnt'] - row['null_cnt']) * 100, 1) if (row['obs_cnt'] - row['null_cnt']) != 0 and row.iloc[2:-3].max() != 0 else 0, axis=1)
    nan_df

In [184]:
# df.pivot_table(index=['customer_type', 'quantity'], aggfunc='size')

# черновик заканчивается

<br>

<br>